import { useState } from 'react'

const MODULES = [
  {
    num:1, icon:'🧠', title:'Mentalidade Financeira',
    desc:'Quebre crenças limitantes sobre dinheiro e desenvolva uma mentalidade de abundância.',
    topics:['Por que não guardo dinheiro?','Gatilhos emocionais do gasto','Os 7 hábitos financeiros'],
    color:'#7C3AED', bg:'#F5F3FF',
    book: {
      title:'Mentalidade Financeira: Do Caos ao Controle',
      pages: [
        { title:'Introdução', content:`Você já se perguntou por que, mesmo ganhando mais, continua sem dinheiro no final do mês?\n\nA resposta raramente está na matemática. Ela está na sua cabeça.\n\nEste módulo é uma jornada ao interior da sua relação com o dinheiro. Vamos desafiar crenças que você carrega desde a infância, identificar os gatilhos emocionais que te fazem gastar por impulso e construir uma mentalidade que sustente riqueza real e duradoura.\n\nNão existe atalho. Mas existe um caminho — e ele começa aqui.` },
        { title:'Capítulo 1: Por que você não guarda dinheiro?', content:`90% das pessoas que não conseguem poupar têm um problema de COMPORTAMENTO, não de matemática.\n\nAs 5 razões mais comuns:\n\n1. IDENTIDADE FINANCEIRA: "Sou uma pessoa que gasta" — você se define assim sem perceber. Mudar finanças exige mudar a história que conta sobre si mesmo.\n\n2. GRATIFICAÇÃO IMEDIATA: O cérebro prefere R$100 hoje a R$150 em 30 dias. Isso é biologia, não fraqueza. Mas pode ser treinado.\n\n3. AUSÊNCIA DE OBJETIVOS: Sem um "para quê" claro, qualquer gasto parece justificável. A reserva de emergência compete com o jantar de hoje — e perde.\n\n4. AMBIENTE SABOTADOR: Suas amizades, redes sociais e hábitos de consumo criam um ambiente que drena seu dinheiro.\n\n5. AUSÊNCIA DE SISTEMA: Poupar por força de vontade não funciona. Você precisa de um sistema automático que funcione mesmo quando você está cansado ou estressado.\n\n💡 Exercício: Escreva sua principal crença sobre dinheiro. Pergunte-se: "De onde veio essa crença? Ela ainda é verdade?"` },
        { title:'Capítulo 2: Psicologia do Dinheiro', content:`Morgan Housel, no livro "A Psicologia do Dinheiro", afirma: "Ser bom com dinheiro tem pouco a ver com inteligência e muito a ver com comportamento."\n\nOS 3 VIESES MAIS CUSTOSOS:\n\n🎯 Viés do Presente: Preferir R$100 agora a R$150 em 30 dias, mesmo que o retorno seja absurdo. Solução: pergunte "Meu eu futuro vai agradecer essa decisão?"\n\n🎯 Efeito Ancoragem: Achar que R$500 é barato porque o produto ao lado custa R$2.000. O preço de referência distorce seu julgamento. Sempre compare com o custo real, não com o produto mais caro.\n\n🎯 Ilusão do Dinheiro: Focar no valor nominal sem considerar a inflação. R$1.000 em 2010 comprava muito mais que R$1.000 hoje. Poupança que rende menos que o IPCA está perdendo valor em termos reais.\n\n📖 Leitura recomendada: "A Psicologia do Dinheiro" — Morgan Housel` },
        { title:'Capítulo 3: Os 7 Hábitos Financeiros', content:`HÁBITO 1 — Pague-se primeiro\nAssim que receber, transfira automaticamente 10% a 20% para investimentos ANTES de pagar qualquer coisa. Trate-se como seu credor mais importante.\n\nHÁBITO 2 — Registre tudo\nSem dados, não há decisão. Use o Munguba Finance para registrar cada centavo. O que não é medido não pode ser melhorado.\n\nHÁBITO 3 — Defina objetivos com datas\n"Quero economizar" não é um objetivo. "Quero ter R$10.000 investidos até dezembro de 2025" é um objetivo. Metas vagas geram resultados vagos.\n\nHÁBITO 4 — Crie sistemas, não discipline-se\nAuto-débito para investimentos, cartão sem crédito rotativo, regra das 48 horas para compras acima de R$200.\n\nHÁBITO 5 — Estude uma hora por semana\nO retorno sobre o investimento em conhecimento financeiro é infinito. Uma hora de estudo por semana pode valer anos de juros perdidos.\n\nHÁBITO 6 — Revise mensalmente\nSepare 30 minutos por mês para olhar suas finanças. O que foi bem? O que saiu do controle? O que vai mudar?\n\nHÁBITO 7 — Comemore o progresso\nFinanças é uma maratona. Pequenas vitórias merecem reconhecimento — de forma que não destrua o progresso.` },
        { title:'Capítulo 4: Riqueza Invisível', content:`"Riqueza é o que você não vê."\n— Morgan Housel\n\nA maior armadilha da sociedade moderna é confundir aparência de riqueza com riqueza real.\n\nA DIFERENÇA FUNDAMENTAL:\n• Renda alta ≠ riqueza\n• Carro caro ≠ sucesso financeiro\n• Casa grande ≠ patrimônio\n\nA riqueza real é o que SOBRA depois de pagar tudo. É o investimento que cresce enquanto você dorme. É a liberdade de dizer não a um emprego ruim.\n\nO PARADOXO DA RIQUEZA VISÍVEL:\nQuando você compra um carro de R$200.000 para impressionar as pessoas, está transferindo patrimônio para outra pessoa enquanto deprecia um ativo.\n\nAs pessoas mais ricas que você conhece frequentemente são as mais discretas. Isso não é coincidência — é a razão pela qual são ricas.\n\n💡 Pergunta reflexiva: Você está construindo riqueza real ou aparência de riqueza?` },
        { title:'Capítulo 5: Gatilhos Emocionais', content:`Compra emocional é responsável por 70% dos gastos não planejados.\n\nOS 6 PRINCIPAIS GATILHOS:\n\n😰 ANSIEDADE: "Trabalhei muito, mereço." Comprar para aliviar o estresse — o alívio dura horas, a conta dura meses.\n\n😔 TRISTEZA: Retail therapy — comprar para preencher um vazio emocional. Funciona por 20 minutos.\n\n🤝 PERTENCIMENTO: Gastar para parecer parte de um grupo, manter status ou não decepcionar amigos.\n\n😤 RAIVA: "Estou bravo, vou me dar um presente." Decisões financeiras tomadas com raiva são sempre ruins.\n\n😊 EUFORIA: Na alta, você acha que tudo vai bem para sempre — e gasta como se fosse. A euforia financeira é a mãe do arrependimento.\n\n😨 MEDO: Comprar por FOMO (Fear Of Missing Out) — "E se o preço subir?" — especialmente em investimentos.\n\n🛠️ FERRAMENTAS PRÁTICAS:\n• Regra das 48 horas: compras acima de R$200 esperam 2 dias\n• Lista de desejos: se ainda quiser em 1 semana, considere\n• Pergunta mágica: "Estou comprando por necessidade ou emoção?"` },
        { title:'Capítulo 6: Ambiente e Influências', content:`Jim Rohn dizia: "Você é a média das 5 pessoas com quem passa mais tempo."\n\nIsso vale também para dinheiro.\n\nO AMBIENTE FINANCEIRO INVISÍVEL:\n\n📱 Redes sociais: você vê o melhor da vida dos outros — viagens, restaurantes, compras. Isso cria um padrão de comparação irreal e constante pressão para consumir.\n\n👥 Grupo social: se seus amigos jantam em lugares caros toda semana, você vai gastar para manter o ritmo. Não é fraqueza — é psicologia humana.\n\n📺 Publicidade: uma pessoa média vê 4.000 anúncios por dia. Cada um é projetado por especialistas para criar desejo.\n\nCOMO REDESENHAR SEU AMBIENTE:\n✅ Siga criadores de conteúdo financeiro nas redes sociais\n✅ Converse abertamente sobre dinheiro com pessoas que admira financeiramente\n✅ Desinstale apps de compra do celular ou dificulte o acesso\n✅ Cancele e-mails de promoção de lojas\n✅ Leia 1 livro de finanças pessoais por trimestre\n\nAmbiente bom > força de vontade. Sempre.` },
        { title:'Capítulo 7: Construindo Sua Identidade Financeira', content:`A mudança financeira duradoura começa com uma mudança de identidade.\n\nNão é "eu deveria poupar mais".\nÉ "eu sou uma pessoa que poupa e investe".\n\nA diferença parece sutil mas é transformadora.\n\nCOMO CONSTRUIR NOVA IDENTIDADE:\n\n1. PEQUENAS VITÓRIAS: Cada vez que você resiste a uma compra por impulso, você vota na identidade de pessoa financeiramente disciplinada.\n\n2. LINGUAGEM: Substitua "não posso pagar" por "escolho não priorizar isso agora". Recupera o senso de agência.\n\n3. COMUNIDADE: Encontre pessoas com objetivos financeiros similares. Fóruns, grupos, mentorias.\n\n4. RITUAIS: Revisão mensal das finanças, transferência automática no dia do pagamento, leitura semanal sobre finanças.\n\n5. CELEBRAÇÕES: Cada milestone merece reconhecimento — primeira reserva completa, primeiro investimento, primeiro dividendo recebido.\n\n🌳 A árvore Munguba cresce lentamente, mas suas raízes são profundas e sua sombra, generosa. Assim é a riqueza real.` },
        { title:'Capítulo 8: Dívidas — Entendendo o Inimigo', content:`Dívida não é necessariamente ruim. Dívida cara é devastadora.\n\nDÍVIDA BOA vs DÍVIDA RUIM:\n\n✅ Dívida boa: financia algo que gera retorno\n• Financiamento de imóvel (patrimônio)\n• Empréstimo para educação que aumenta renda\n• Capital de giro para negócio lucrativo\n\n❌ Dívida ruim: financia consumo que se deprecia\n• Cartão de crédito (juros de até 400% a.a.)\n• Cheque especial (~150% a.a.)\n• Crédito pessoal para compras supérfluas\n• Parcelamento sem juros de algo que você não precisava\n\nOS NÚMEROS QUE ASSUSTAM:\nR$1.000 no cartão de crédito, pagando mínimo, pode se transformar em R$5.000 em 2 anos.\n\nESTRATÉGIA AVALANCHE (matematicamente superior):\nPague primeiro a dívida com maior taxa de juros.\n\nESTRATÉGIA BOLA DE NEVE (psicologicamente superior):\nPague primeiro a menor dívida para criar momentum.\n\nEscolha a que você vai seguir — executar o plano imperfeito é melhor que planejar o plano perfeito.` },
        { title:'Capítulo 9: O Poder dos Juros Compostos', content:`Einstein teria chamado os juros compostos de "a oitava maravilha do mundo".\n\nA MÁGICA DOS JUROS COMPOSTOS:\nVocê ganha juros sobre os juros que já ganhou.\n\nEXEMPLO PRÁTICO:\nR$ 1.000 investidos a 12% ao ano:\n• Ano 1: R$ 1.120\n• Ano 5: R$ 1.762\n• Ano 10: R$ 3.106\n• Ano 20: R$ 9.646\n• Ano 30: R$ 29.960\n\nA REGRA DOS 72:\nDivida 72 pela taxa de juros anual para saber em quantos anos seu dinheiro dobra.\n72 ÷ 12% = 6 anos para dobrar.\n\nO CUSTO DO TEMPO:\nInvestir R$500/mês dos 25 aos 65 anos a 10% a.a. = R$2.659.260\nInvestir R$500/mês dos 35 aos 65 anos a 10% a.a. = R$987.164\n\n10 anos de diferença = R$1.672.096 a menos.\n\nNão é quanto você investe. É por quanto tempo você investe.\n\nComece hoje. O segundo melhor momento é amanhã.` },
        { title:'Capítulo 10: Seu Plano de Ação', content:`Chegou a hora de sair da teoria e entrar em ação.\n\n🎯 SEU PLANO DOS PRÓXIMOS 30 DIAS:\n\nSEMANA 1 — DIAGNÓSTICO:\n□ Registre TODOS os gastos no Munguba Finance\n□ Calcule sua renda líquida mensal\n□ Identifique os 3 maiores gastos desnecessários\n\nSEMANA 2 — RESERVA:\n□ Abra uma conta separada para emergências\n□ Calcule quanto você precisa (3-6 meses de gastos)\n□ Faça a primeira transferência, mesmo que seja R$50\n\nSEMANA 3 — SISTEMA:\n□ Configure transferência automática no dia do pagamento\n□ Defina seu objetivo financeiro de 12 meses (específico!)\n□ Cancele pelo menos 2 assinaturas que não usa\n\nSEMANA 4 — CONHECIMENTO:\n□ Leia 30 minutos sobre finanças\n□ Revise os gastos da semana\n□ Comemore cada pequena vitória\n\n🌳 LEMBRE-SE:\n"A jornada de mil milhas começa com um único passo."\n\nVocê não precisa fazer tudo de uma vez. Precisa fazer a coisa certa, repetidamente, por tempo suficiente. Esse é o segredo de toda riqueza duradoura.` },
      ]
    }
  },
  {
    num:2, icon:'📊', title:'Controle Financeiro',
    desc:'Domine seu fluxo de caixa e saiba exatamente para onde vai cada centavo.',
    topics:['Método 50-30-20','Orçamento base zero','Planilha de controle'],
    color:'#076B3E', bg:'#DCFCE7',
    book: {
      title:'Controle Financeiro: Cada Centavo Conta',
      pages: [
        { title:'Introdução', content:`"Não é quanto você ganha. É quanto você guarda."\n\nEssa frase simples resume décadas de pesquisa sobre comportamento financeiro.\n\nNeste módulo você vai aprender a transformar sua relação com o dinheiro através de sistemas práticos e eficazes. Não precisará de planilhas complicadas ou formação em economia.\n\nPrecisará apenas de honestidade consigo mesmo e disposição para mudar alguns hábitos.\n\nVamos começar?` },
        { title:'Capítulo 1: O Método 50-30-20', content:`Criado pela senadora americana Elizabeth Warren em seu livro "All Your Worth", o método 50-30-20 é uma das abordagens mais eficazes e simples de orçamento.\n\nA DIVISÃO:\n🔵 50% — NECESSIDADES\nMoradia, alimentação básica, transporte para trabalho, saúde, contas essenciais (água, luz, internet).\n\n🟡 30% — DESEJOS\nRestaurantes, lazer, streaming, roupas além do necessário, viagens, hobbies.\n\n🟢 20% — FUTURO\nReserva de emergência, investimentos, pagamento de dívidas acima do mínimo.\n\nEXEMPLO PRÁTICO com R$5.000 líquidos:\n• Necessidades: R$2.500 (aluguel R$1.200, alimentação R$800, transporte R$300, saúde R$200)\n• Desejos: R$1.500 (lazer R$500, restaurantes R$400, roupas R$300, assinaturas R$300)\n• Futuro: R$1.000 (investimentos R$700, reserva R$300)\n\n⚠️ ADAPTE À SUA REALIDADE:\nSe suas necessidades consomem 70%, comece reduzindo desejos e aumentando o futuro gradualmente. O objetivo não é perfeição imediata, é progresso constante.` },
        { title:'Capítulo 2: Orçamento Base Zero', content:`O orçamento base zero é mais rigoroso que o 50-30-20, mas extremamente poderoso.\n\nO PRINCÍPIO:\nRenda - Despesas = 0\n\nIsso não significa gastar tudo — significa que cada real tem uma destinação específica. Incluindo os investimentos.\n\nCOMO FUNCIONA:\n1. Liste sua renda líquida mensal: R$5.000\n2. Liste TODAS as despesas fixas: R$3.200\n3. Separe os investimentos como "despesa": R$1.000\n4. O que sobra é para despesas variáveis: R$800\n\nVANTAGENS:\n✅ Elimina gastos "invisíveis"\n✅ Força priorização consciente\n✅ Identifica vazamentos financeiros\n✅ Maximiza taxa de poupança\n\nDESVANTAGENS:\n❌ Requer mais disciplina e acompanhamento\n❌ Pode ser muito restritivo inicialmente\n❌ Precisa ser revisado quando há mudanças de renda\n\n💡 DICA: Comece com o 50-30-20 por 3 meses. Depois migre para base zero se quiser mais controle.` },
        { title:'Capítulo 3: Gastos Fixos vs Variáveis', content:`GASTOS FIXOS: valores que não mudam todo mês\n• Aluguel/financiamento\n• Mensalidade de escola\n• Plano de saúde\n• Internet e telefone\n• Assinaturas (Netflix, Spotify)\n• Academia\n\nGASTOS VARIÁVEIS: mudam conforme uso e escolhas\n• Alimentação\n• Combustível\n• Lazer\n• Roupas\n• Delivery\n• Compras diversas\n\nPOR QUE IMPORTA ESSA DISTINÇÃO?\n\nGastos fixos são mais difíceis de reduzir no curto prazo mas, uma vez cortados, geram economia permanente.\n\nGastos variáveis são mais fáceis de reduzir mas exigem atenção constante.\n\n🎯 ESTRATÉGIA:\n• Revise gastos fixos anualmente — renegocie contratos, cancele o que não usa\n• Estabeleça limites para cada categoria variável\n• Use o Munguba Finance para categorizar e monitorar ambos\n\nIdentificar onde seu dinheiro vai é o primeiro passo para decidir onde ele deveria ir.` },
        { title:'Capítulo 4: Armadilhas do Consumo Moderno', content:`A economia moderna foi projetada para maximizar seu consumo — não seu bem-estar.\n\nAS 7 ARMADILHAS MAIS COMUNS:\n\n1. PARCELAMENTO PSICOLÓGICO\n"São apenas R$49,90 por mês" — 12 parcelas = R$598,80. Somando 5 dessas "pechingas" = R$2.994/ano.\n\n2. DESCONTO ILUSÓRIO\n"Economizei R$200 comprando em promoção" — mas era algo que não precisava. Não economizou R$200, gastou R$300.\n\n3. FRETE GRÁTIS ACIMA DE X\n"Vou colocar mais itens para ter frete grátis de R$20" — gastou R$80 a mais para "economizar" R$20.\n\n4. CASHBACK SEDUTOR\n"Ganho cashback" — mas gasta mais para ganhar menos de volta.\n\n5. CLUBE DE ASSINATURAS\n"É baratinho por mês" — some todas as assinaturas que você mal usa.\n\n6. "MERECI"\n"Trabalhei muito este mês, mereço" — compra emocional com justificativa racional.\n\n7. COMPARAÇÃO SOCIAL\n"Meu amigo tem, eu também preciso" — gastar para manter aparência de igualdade.\n\n🛡️ DEFESA: Antes de qualquer compra acima de R$100, faça a pergunta: "Se eu não comprasse isso, o que faria com esse dinheiro?"` },
        { title:'Capítulo 5: O Fluxo de Caixa Pessoal', content:`Empresas de sucesso são obsessivas com fluxo de caixa. Você deveria ser também.\n\nFLUXO DE CAIXA PESSOAL:\nEntradas - Saídas = Resultado do período\n\nResultado positivo → acúmulo de patrimônio\nResultado negativo → erosão do patrimônio\n\nCOMO MONITORAR:\n1. Registre toda entrada de dinheiro (salário, freelance, dividendos, vendas)\n2. Registre toda saída (despesas fixas, variáveis, investimentos)\n3. Calcule o resultado semanal e mensal\n4. Compare com o mês anterior\n\nINDICADORES DO SEU FLUXO:\n\n🟢 Saudável:\n• Investimentos ≥ 10% da renda\n• Resultado mensal positivo por pelo menos 10 de 12 meses\n• Reserva de emergência completa\n\n🟡 Atenção:\n• Investimentos < 10% da renda\n• Resultado negativo em 3-4 meses por ano\n• Reserva de emergência incompleta\n\n🔴 Crítico:\n• Resultado negativo na maioria dos meses\n• Sem reserva\n• Usando crédito para despesas básicas` },
        { title:'Capítulo 6: Metas SMART de Finanças', content:`Metas vagas geram resultados vagos.\n\n"Quero economizar dinheiro" não é uma meta.\n"Quero ter R$15.000 investidos em Tesouro Selic até 31/12/2025" é uma meta.\n\nO MÉTODO SMART:\n\nS — Específica: "R$15.000 em Tesouro Selic"\nM — Mensurável: posso acompanhar mensalmente\nA — Atingível: baseada na minha renda e possibilidades\nR — Relevante: conectada a um objetivo maior (viagem, casa, independência)\nT — Temporal: tem data de conclusão\n\nEXEMPLOS DE METAS SMART:\n• Quitar o cartão de crédito de R$3.200 em 6 meses (R$533/mês)\n• Investir R$500/mês por 12 meses (R$6.000 + juros)\n• Reduzir gastos com delivery de R$600 para R$200/mês em 3 meses\n• Completar reserva de emergência de R$12.000 em 18 meses\n\n💡 DICA PODEROSA:\nEscreva suas metas financeiras e coloque-as onde vê todos os dias. Estudos mostram que pessoas que escrevem metas têm 42% mais chance de alcançá-las.` },
        { title:'Capítulo 7: Automatizando as Finanças', content:`A força de vontade é um recurso escasso e esgotável.\n\nO SEGREDO DOS RICOS: eles não dependem de disciplina — dependem de sistemas automáticos.\n\nO QUE AUTOMATIZAR:\n\n1. INVESTIMENTOS NO DIA DO PAGAMENTO\nConfigure uma transferência automática para o dia em que recebe. Você não vai sentir falta do que nunca está na conta corrente.\n\n2. PAGAMENTO DE CONTAS FIXAS\nDébito automático elimina atrasos e multas — e o estresse de lembrar.\n\n3. RESGATE DE CASHBACK\nAproveite benefícios existentes sem precisar lembrar.\n\n4. REVISÃO MENSAL AGENDADA\n30 minutos, todo dia 1 do mês, para revisar o mês anterior e planejar o próximo.\n\nO PRINCÍPIO DO MENOS É MAIS:\nConta corrente: apenas o necessário para despesas do mês\nConta investimentos: tudo que você não vai gastar nos próximos 3 meses\n\nQuando o dinheiro "desaparece" automaticamente para investimentos, você adapta seus gastos ao que sobra — não o contrário.` },
        { title:'Capítulo 8: Revisando e Ajustando', content:`Um orçamento não é uma prisão — é uma bússola.\n\nA REVISÃO MENSAL (30 minutos):\n\n1. QUANTO ENTROU? (10 minutos)\n• Some todas as fontes de renda\n• Compare com o mês anterior e com a meta\n\n2. QUANTO SAIU E PARA ONDE? (10 minutos)\n• Abra o Munguba Finance e revise as categorias\n• Identifique onde ultrapassou o orçamento\n• Identifique gastos não registrados\n\n3. O QUE APRENDER E MUDAR? (10 minutos)\n• O que funcionou bem?\n• O que saiu do controle?\n• Que ajuste precisa ser feito para o próximo mês?\n\nPERGUNTAS REFLEXIVAS:\n• Meu padrão de gastos reflete meus valores e prioridades reais?\n• Onde estou pagando por algo que não uso?\n• Qual categoria mais me surpreendeu?\n• Estou me aproximando dos meus objetivos?\n\nFinanças saudáveis não são estáticas — evoluem com você.` },
        { title:'Capítulo 9: Indicadores Financeiros Pessoais', content:`O que não é medido não pode ser melhorado.\n\nSEUS PRINCIPAIS INDICADORES:\n\n📊 TAXA DE POUPANÇA\nFórmula: (Valor investido ÷ Renda líquida) × 100\nReferência: 20% é excelente, 10% é bom, abaixo de 5% é preocupante\n\n📊 ÍNDICE DE ENDIVIDAMENTO\nFórmula: (Dívidas mensais ÷ Renda líquida) × 100\nReferência: abaixo de 30% é saudável, acima de 40% é perigoso\n\n📊 PATRIMÔNIO LÍQUIDO\nFórmula: Ativos (o que você tem) - Passivos (o que você deve)\nMeta: crescer esse número todo mês\n\n📊 MESES DE AUTONOMIA\nFórmula: Patrimônio líquido ÷ Gastos mensais\nSignificado: por quantos meses você sobreviveria sem renda?\n\n📊 COBERTURA DE EMERGÊNCIA\nFórmula: Reserva de emergência ÷ Gastos mensais\nReferência: mínimo 3, ideal 6 para CLT, 12 para autônomo\n\nAcompanhe esses números mensalmente. Você vai se surpreender com a clareza que eles trazem.` },
        { title:'Capítulo 10: Construindo Hábitos Duradouros', content:`Você chegou ao final deste módulo. Mas o trabalho real começa agora.\n\nA CIÊNCIA DOS HÁBITOS:\nPesquisas mostram que demora em média 66 dias para um comportamento se tornar hábito automático — não 21 dias como se acreditava.\n\nO LOOP DO HÁBITO FINANCEIRO:\n🔔 Gatilho → 🎬 Rotina → 🏆 Recompensa\n\nEXEMPLO:\nGatilho: chegou o salário\nRotina: transferência automática de 20% para investimentos\nRecompensa: ver o saldo de investimentos crescer (e a paz que isso traz)\n\nSEUS PRÓXIMOS 66 DIAS:\n✅ Dia 1-7: Registrar 100% dos gastos no Munguba Finance\n✅ Dia 8-14: Categorizar e identificar desperdícios\n✅ Dia 15-30: Aplicar o método 50-30-20\n✅ Dia 31-45: Configurar automação dos investimentos\n✅ Dia 46-66: Primeira revisão mensal e ajustes\n\n🌳 PENSAMENTO FINAL:\nA árvore Munguba não cresce da noite para o dia. Mas cada ação correta — cada registro, cada investimento, cada "não" ao impulso — é uma raiz mais funda.\n\nSua floresta financeira começa hoje.` },
      ]
    }
  },
  {
    num:3, icon:'💳', title:'Saindo das Dívidas',
    desc:'Estratégias comprovadas para eliminar dívidas e recuperar a paz financeira.',
    topics:['Método avalanche vs bola de neve','Renegociação de dívidas','Histórico de crédito'],
    color:'#D63333', bg:'#FEF2F2',
    book: {
      title:'Zero Dívidas: Liberdade Financeira Real',
      pages: [
        { title:'Introdução', content:`Dívida é a escravidão do século XXI.\n\nSe você está neste módulo, provavelmente conhece a sensação de acordar às 3 da manhã pensando em contas. De checar o saldo antes de dormir e não conseguir dormir depois.\n\nA boa notícia: dívida é um problema com solução. E a solução é mais simples do que parece — embora não seja fácil.\n\nEste módulo é um plano de batalha. Não uma teoria acadêmica — um roteiro prático para você sair do vermelho e nunca mais voltar.` },
        { title:'Capítulo 1: Diagnóstico Completo', content:`Antes de qualquer estratégia, você precisa conhecer seu inimigo.\n\nFILÉ COMPLETO DAS DÍVIDAS:\nPara cada dívida, anote:\n• Credor (banco, loja, pessoa)\n• Saldo devedor atual\n• Taxa de juros mensal e anual\n• Parcela mínima mensal\n• Data de vencimento\n\nEXEMPLO DE FICHA:\n1. Cartão Banco X: R$5.000 | 15% a.m. | mínimo R$250 | vence dia 10\n2. Cheque especial: R$2.000 | 12% a.m. | variável | vence dia 30\n3. Empréstimo pessoal: R$8.000 | 3% a.m. | R$400 | vence dia 15\n\nPOR QUE ISSO É CRUCIAL:\nSem clareza total, você não consegue priorizar. E sem priorização, paga mais juros do que deveria.` },
        { title:'Capítulo 2: A Anatomia dos Juros', content:`Para vencer a dívida, você precisa entender como os juros te destroem.\n\nJUROS SIMPLES:\nR$1.000 a 10% ao ano = R$100 por ano = R$1.100 após 1 ano\n\nJUROS COMPOSTOS (a realidade do crédito):\nR$1.000 a 10% ao mês (típico do cartão):\n• Mês 1: R$1.100\n• Mês 3: R$1.331\n• Mês 6: R$1.772\n• Mês 12: R$3.138\n\nSIM — R$1.000 vira R$3.138 em 12 meses no cartão de crédito.\n\nAS TAXAS QUE VOCÊ PAGA:\n🔴 Cartão de crédito (rotativo): até 400% a.a.\n🔴 Cheque especial: até 200% a.a.\n🟡 Empréstimo pessoal: 30% a 120% a.a.\n🟡 CDC (financeira): 20% a 60% a.a.\n🟢 Crédito consignado: 6% a 30% a.a.\n🟢 Financiamento imobiliário: 9% a 14% a.a.\n\nEssa lista determina a ORDEM de pagamento das dívidas.` },
        { title:'Capítulo 3: Método Avalanche', content:`O método matematicamente mais eficiente para eliminar dívidas.\n\nCOMO FUNCIONA:\n1. Pague o mínimo de TODAS as dívidas\n2. Direcione todo dinheiro extra para a dívida com MAIOR taxa de juros\n3. Quando essa dívida zerar, direcione tudo para a próxima maior taxa\n4. Repita até zerar tudo\n\nEXEMPLO PRÁTICO:\nDívida A: R$5.000 a 15% ao mês → prioridade 1\nDívida B: R$2.000 a 12% ao mês → prioridade 2\nDívida C: R$8.000 a 3% ao mês → prioridade 3\n\nVocê paga mínimos de B e C, e joga tudo em A primeiro — mesmo que A seja a maior.\n\nVANTAGEM: Paga menos juros no total\nDESVANTAGEM: Pode demorar mais para "ver resultado"\n\n💡 IDEAL PARA: pessoas analíticas que se motivam pelo racional e pela matemática.` },
        { title:'Capítulo 4: Método Bola de Neve', content:`Popularizado por Dave Ramsey, o método bola de neve prioriza a psicologia sobre a matemática.\n\nCOMO FUNCIONA:\n1. Pague o mínimo de TODAS as dívidas\n2. Direcione todo dinheiro extra para a dívida de MENOR saldo\n3. Quando essa dívida zerar, some o valor que pagava + extra para a próxima menor\n4. A "bola de neve" cresce a cada dívida eliminada\n\nEXEMPLO:\nDívida A: R$2.000 (menor) → prioridade 1\nDívida B: R$5.000 → prioridade 2\nDívida C: R$8.000 (maior) → prioridade 3\n\nVANTAGEM: Vitórias rápidas criam motivação e momentum\nDESVANTAGEM: Paga mais juros no total\n\nA PESQUISA DIZ:\nEstudos da Harvard Business School mostram que a maioria das pessoas é mais bem-sucedida com a bola de neve — a motivação das pequenas vitórias supera a vantagem matemática da avalanche.\n\n🎯 REGRA DE OURO: O melhor método é o que você vai EXECUTAR.` },
        { title:'Capítulo 5: Renegociação de Dívidas', content:`Muitos não sabem, mas dívidas são negociáveis. Especialmente as antigas.\n\n5 ESTRATÉGIAS DE RENEGOCIAÇÃO:\n\n1. NEGOCIE DIRETAMENTE COM O CREDOR\nLigue, seja honesto sobre sua situação. Credores preferem receber menos a não receber nada. Desconto de 30% a 70% em dívidas antigas é comum.\n\n2. PLATAFORMA SERASA LIMPA NOME\nO Serasa tem parceria com diversas empresas e oferece descontos exclusivos online.\n\n3. FEIRÃO LIMPA NOME\nEventos periódicos com condições especiais de negociação.\n\n4. PROCON E DEFENSORIA PÚBLICA\nEm casos de abuso ou impossibilidade de pagamento.\n\n5. CONSOLIDAÇÃO DE DÍVIDAS\nUm único empréstimo (com taxa menor) para quitar vários — cuidado para não criar nova dívida cara.\n\nO QUE PEDIR NA NEGOCIAÇÃO:\n• Redução do saldo devedor\n• Redução da taxa de juros\n• Prazo maior (mas cuidado — prazo maior pode significar mais juros)\n• Entrada menor\n\n⚠️ DOCUMENTE TUDO por escrito antes de pagar qualquer valor negociado.` },
        { title:'Capítulo 6: Score de Crédito', content:`O score de crédito é sua reputação financeira — um número de 0 a 1000 que determina quanto você paga de juros e quais créditos consegue.\n\nCLASSIFICAÇÃO DO SERASAS:\n• 0-300: Muito baixo (risco alto)\n• 301-500: Baixo\n• 501-700: Bom\n• 701-900: Muito bom\n• 901-1000: Excelente\n\nO QUE AFETA O SCORE:\n⬆️ AUMENTA:\n• Pagar contas em dia\n• Tempo com nome limpo\n• Relacionamento com instituições financeiras\n• Dados atualizados no Cadastro Positivo\n\n⬇️ DIMINUI:\n• Dívidas em atraso\n• Nome no SPC/Serasa\n• Muitas consultas ao CPF em pouco tempo\n• Alta utilização do limite do cartão\n\nCOMO MELHORAR RÁPIDO:\n1. Quite as dívidas em atraso\n2. Pague tudo em dia por pelo menos 6 meses\n3. Mantenha dados cadastrais atualizados\n4. Ative o Cadastro Positivo (valoriza histórico de pagamentos)` },
        { title:'Capítulo 7: Cartão de Crédito — Aliado ou Inimigo?', content:`O cartão de crédito é uma das ferramentas financeiras mais poderosas — e mais perigosas.\n\nCOMO USAR O CARTÃO A SEU FAVOR:\n\n✅ FAÇA:\n• Use como ferramenta de controle (registro automático de gastos)\n• Aproveite milhas e cashback em compras que faria de qualquer forma\n• Pague SEMPRE o total da fatura no vencimento\n• Mantenha o uso abaixo de 30% do limite (ajuda o score)\n\n❌ NUNCA FAÇA:\n• Pague o mínimo da fatura (entra em rotativo — 400% a.a.)\n• Use o limite como extensão da sua renda\n• Parcelamento "sem juros" de coisas que não pode pagar à vista\n• Faça saque no crédito (juros altíssimos desde o primeiro dia)\n\nA REGRA DE OURO:\nSe você não tem o dinheiro na conta, não coloque no cartão.\n\nO cartão é um intermediário de pagamento — não uma fonte de crédito para o dia a dia.` },
        { title:'Capítulo 8: Vida Pós-Dívidas', content:`O dia em que você quita a última dívida é um dos mais importantes da sua vida financeira.\n\nO QUE FAZER QUANDO FICAR LIVRE:\n\n1. CELEBRE (com moderação e sem gastar!)\nIsso merece reconhecimento. Você superou um desafio enorme.\n\n2. CONSTRUA A RESERVA DE EMERGÊNCIA\nSem ela, qualquer imprevisto te joga de volta nas dívidas.\n\n3. REDIRECIONE O QUE PAGAVA EM DÍVIDAS\nSe pagava R$1.500/mês em parcelas, invista esse valor agora. Você já provou que consegue viver sem ele.\n\n4. APRENDA COM O PASSADO\nO que criou as dívidas? Gasto emocional? Falta de reserva? Renda insuficiente? Identifique e corrija.\n\n5. CRIE BARREIRAS CONTRA NOVAS DÍVIDAS:\n• Não salve cartão de crédito em sites de compra\n• Desinstale apps de compra do celular\n• Implemente a regra das 48 horas para compras grandes\n• Mantenha o Munguba Finance sempre atualizado\n\nA liberdade financeira começa quando você para de trabalhar para pagar o passado e começa a trabalhar para construir o futuro.` },
        { title:'Capítulo 9: Prevenindo Futuras Dívidas', content:`A melhor dívida é a que nunca foi contraída.\n\n7 REGRAS PARA NUNCA MAIS ENDIVIDAR:\n\n1. REGRA DO DINHEIRO NO BOLSO\nSó compre o que você tem dinheiro para pagar agora. O parcelamento sem juros é uma ilusão — você compromete renda futura.\n\n2. RESERVA DE EMERGÊNCIA\n95% das dívidas de consumo começam com um imprevisto sem reserva. Com 3-6 meses de gastos guardados, você está protegido.\n\n3. FUNDO DE COMPRAS GRANDES\nVai precisar de carro, eletrodoméstico, viagem? Crie um fundo específico e poupe mensalmente.\n\n4. SEGURO ADEQUADO\nSeguro de vida, saúde e renda são proteção financeira — não gasto.\n\n5. ORÇAMENTO MENSAL RIGOROSO\nSem orçamento, qualquer compra parece razoável.\n\n6. DIGA NÃO AO CRÉDITO FÁCIL\n"Aprovamos R$20.000 em 5 minutos" é uma armadilha, não um benefício.\n\n7. EDUCAÇÃO FINANCEIRA CONTÍNUA\nContinue aprendendo. Continue no Munguba Finance. O conhecimento é o melhor escudo contra as armadilhas financeiras.` },
        { title:'Capítulo 10: Seu Plano de Saída', content:`Chegou a hora de criar seu plano personalizado de eliminação de dívidas.\n\nPASSO A PASSO:\n\n📋 SEMANA 1 — MAPEAMENTO:\n□ Liste TODAS as dívidas (credor, saldo, taxa, mínimo)\n□ Calcule o total que você deve\n□ Identifique a maior taxa de juros\n\n💰 SEMANA 2 — CORTES:\n□ Identifique R$300-500 de cortes no orçamento mensal\n□ Venda algo que não usa mais\n□ Cancele assinaturas desnecessárias\n\n📞 SEMANA 3 — NEGOCIAÇÃO:\n□ Ligue para os credores com maior taxa\n□ Tente negociar desconto para pagamento à vista\n□ Pesquise no Serasa Limpa Nome\n\n🎯 MÊS 2 EM DIANTE — EXECUÇÃO:\n□ Pague o mínimo de todas as dívidas\n□ Direcione o extra para a prioridade 1\n□ Acompanhe no Munguba Finance\n□ Celebre cada dívida quitada\n\n🌳 VOCÊ CONSEGUE.\nMilhares de pessoas saíram de situações muito piores. Com clareza, sistema e disciplina, a liberdade financeira é inevitável.` },
      ]
    }
  },
  {
    num:4, icon:'🛡️', title:'Reserva de Emergência',
    desc:'Construa um colchão financeiro que te protege de qualquer imprevisto.',
    topics:['Quanto guardar?','Onde guardar?','Tesouro Selic na prática'],
    color:'#0E7490', bg:'#ECFEFF',
    book: {
      title:'Reserva de Emergência: Seu Escudo Financeiro',
      pages: [
        { title:'Introdução', content:`"A reserva de emergência não é uma opção. É o alicerce de tudo."\n\nSem ela, você está a um imprevisto de distância do endividamento.\n\nDemissão inesperada. Carro quebrado. Problema de saúde. Conserto da casa. Qualquer um desses eventos pode destruir anos de planejamento financeiro se você não tiver um colchão de segurança.\n\nEste módulo vai te mostrar quanto guardar, onde guardar e — o mais importante — como construir essa reserva mesmo começando do zero.` },
        { title:'Capítulo 1: Por que a Reserva é Prioridade #1', content:`ANTES DE QUALQUER INVESTIMENTO, você precisa de reserva de emergência.\n\nPOR QUÊ?\n\nSem reserva, um imprevisto te força a:\n• Resgatar investimentos de longo prazo no pior momento\n• Pegar empréstimo com juros altos\n• Usar o cartão de crédito e entrar no rotativo\n• Vender bens com urgência e preço baixo\n\nCOM RESERVA, um imprevisto é apenas um inconveniente — não uma crise.\n\nA MATEMÁTICA:\nSem reserva: imprevisto de R$5.000 → empréstimo a 4% ao mês → R$7.346 em 12 meses (R$2.346 de juros pagos)\n\nCom reserva: mesmo imprevisto de R$5.000 → saca do Tesouro Selic → repõe ao longo de 6 meses\n\nA diferença é de R$2.346 que ficam no seu bolso.\n\nE paz de espírito que não tem preço.` },
        { title:'Capítulo 2: Quanto Você Precisa?', content:`A regra geral é 3 a 6 meses de gastos mensais. Mas a resposta certa depende do seu perfil.\n\nCALCULE SEUS GASTOS MENSAIS ESSENCIAIS:\n• Moradia (aluguel/financiamento + condomínio)\n• Alimentação\n• Transporte\n• Saúde (plano + medicamentos)\n• Contas básicas (água, luz, internet)\n• Educação (escola dos filhos)\n\nExclua gastos de lazer — em uma emergência real você corta isso.\n\nQUANTOS MESES GUARDAR:\n\n✅ 3 meses: empregado CLT estável, renda dupla no lar, poucas dependências\n\n✅ 6 meses: empregado CLT comum, renda única, filhos, dependentes\n\n✅ 12 meses: autônomo, freelancer, empresário, profissão com alta volatilidade de renda\n\nEXEMPLO PRÁTICO:\nGastos essenciais de R$3.500/mês:\n• CLT estável: R$10.500 (3 meses)\n• CLT padrão: R$21.000 (6 meses)\n• Autônomo: R$42.000 (12 meses)` },
        { title:'Capítulo 3: Onde Guardar', content:`A reserva de emergência tem 3 requisitos inegociáveis:\n✅ SEGURANÇA (não pode perder valor nominal)\n✅ LIQUIDEZ (precisa estar disponível em 24-48h)\n✅ RENTABILIDADE (deve no mínimo proteger da inflação)\n\nAS MELHORES OPÇÕES:\n\n🥇 TESOURO SELIC (melhor custo-benefício)\n• Rende: ~13,75% a.a. (acompanha a Selic)\n• Liquidez: D+1 (disponível no próximo dia útil)\n• Risco: praticamente zero (garantido pelo governo)\n• IR: 22,5% (até 180 dias) a 15% (acima de 720 dias)\n• Como investir: qualquer corretora (Rico, XP, NuInvest, Tesouro Direto)\n\n🥈 CDB COM LIQUIDEZ DIÁRIA (100% CDI)\n• Rende: ~99-100% do CDI\n• Liquidez: imediata (D+0)\n• Risco: baixo (FGC garante até R$250k)\n• IR: mesmo do Tesouro Selic\n\n🥉 CONTA REMUNERADA (bancos digitais)\n• Nubank, Inter, C6 Bank: 100% do CDI\n• Liquidez: imediata\n• Facilidade de uso\n\n❌ EVITE:\n• Poupança (rende ~6-7% a.a. — abaixo da inflação)\n• Ações ou FIIs (risco de perdas temporárias)\n• Imóveis (sem liquidez)` },
        { title:'Capítulo 4: Como Construir do Zero', content:`"Não tenho dinheiro para reserva" — a resposta é: construir aos poucos.\n\nESTRATÉGIA DO CRESCIMENTO GRADUAL:\n\nMES 1-3: META MICRO (R$1.000)\nObjetivo: ter qualquer reserva é melhor que zero\nAção: separe R$333/mês ou qualquer valor que conseguir\n\nMES 4-12: META PEQUENA (1 mês de gastos)\nObjetivo: cobrir o imprevisto mais comum\nAção: aumente a contribuição mensal\n\nMES 13-24: META PADRÃO (3-6 meses)\nObjetivo: proteção real contra eventos sérios\nAção: contribuição automática no dia do pagamento\n\nFONTES EXTRAS PARA ACELERAR:\n• 13º salário → 100% para reserva\n• Restituição do IR → reserva\n• Venda de itens que não usa → reserva\n• Hora extra, freelance → reserva\n\nDICA PODEROSA:\nAbra uma conta separada exclusiva para a reserva. "Longe dos olhos, longe dos gastos."` },
        { title:'Capítulo 5: Tesouro Selic na Prática', content:`Passo a passo para investir no Tesouro Selic pela primeira vez.\n\nOPÇÃO 1: PELO TESOURO DIRETO (SITE OFICIAL)\n1. Acesse www.tesourodireto.com.br\n2. Crie sua conta (precisa de CPF e banco)\n3. Escolha "Tesouro Selic"\n4. Invista a partir de R$30\n\nOPÇÃO 2: PELA CORRETORA (mais prático)\n1. Abra conta em Rico, XP, NuInvest (gratuito)\n2. Transfira via TED ou PIX\n3. Vá em "Renda Fixa" → "Tesouro Direto"\n4. Escolha "Tesouro Selic" e invista\n\nIMPORTANTE SOBRE TAXAS:\n• Taxa de custódia B3: 0,20% a.a. sobre o valor investido\n• Taxa de administração: varia por corretora (muitas cobram zero)\n• IR: retido na fonte no resgate\n\nCOMO FUNCIONA O RESGATE:\n• Solicite o resgate na corretora\n• Dinheiro cai na sua conta no próximo dia útil (D+1)\n• Sem necessidade de justificar\n\nRENTABILIDADE ESPERADA:\nA 13,75% a.a.: R$10.000 vira ~R$11.375 brutos em 12 meses, ou ~R$11.180 líquidos (descontando IR de 17,5%).` },
        { title:'Capítulo 6: Quando Usar a Reserva', content:`A reserva é para EMERGÊNCIAS — não para qualquer imprevisto.\n\n✅ USE A RESERVA PARA:\n• Perda repentina de emprego ou renda\n• Emergência médica não coberta pelo plano de saúde\n• Conserto urgente de carro ou casa (necessidades básicas)\n• Morte ou doença grave na família\n• Crise de renda por situação inesperada\n\n❌ NÃO USE PARA:\n• Viagem de férias (isso é fundo de viagem)\n• Compra de presente (isso é orçamento do mês)\n• Promoção irresistível (isso não é emergência)\n• Oportunidade de investimento (isso é especulação)\n\nA REGRA DO "SIGO SEM ELA?"\nAntes de resgatar a reserva, pergunte: "Consigo passar os próximos 30 dias sem usar isso?" Se a resposta for sim, não é emergência.\n\nDEPOIS DO RESGATE:\nSempre que usar, reponha o mais rápido possível. A reserva que foi usada não está mais te protegendo.` },
        { title:'Capítulo 7: Reserva vs Investimento', content:`Uma confusão comum: "Já tenho ações/FIIs. Isso conta como reserva?"\n\nNÃO. Aqui está o porquê:\n\nO PROBLEMA DAS AÇÕES NA EMERGÊNCIA:\nVocê perde o emprego em fevereiro — justamente quando a bolsa cai 20%. Para ter o dinheiro, você vende as ações com prejuízo. A reserva virou buraco.\n\nO PROBLEMA DOS FIIs NA EMERGÊNCIA:\nPrecisa de R$15.000 com urgência. Seu FII está desvalorizado 15%. Você vende com perda e perde os dividendos futuros.\n\nA DISTINÇÃO FUNDAMENTAL:\n• Reserva de emergência: Tesouro Selic, CDB líquido — sem risco, sem volatilidade\n• Investimentos: ações, FIIs, ETFs — com risco, com volatilidade\n\nA SEQUÊNCIA CORRETA:\n1. Reserva de emergência completa\n2. APENAS DEPOIS comece a investir em renda variável\n\nNão existe atalho seguro nessa sequência.` },
        { title:'Capítulo 8: Automatizando a Construção', content:`O segredo para construir reserva com consistência: automatização.\n\nO SISTEMA DE 3 CONTAS:\n\n📱 CONTA CORRENTE (banco principal)\n• Recebe o salário\n• Paga as contas do mês\n• Mantém apenas o necessário para o mês\n\n🏦 CONTA RESERVA (banco digital separado)\n• CDB liquidez diária ou Tesouro Selic\n• Nunca recebe transferência manual\n• Transferência automática todo dia do salário\n\n📈 CONTA INVESTIMENTOS (corretora)\n• Ações, FIIs, ETFs\n• Só começa depois da reserva completa\n• Transferência automática mensal\n\nPOR QUE 3 CONTAS?\nA separação física cria uma barreira psicológica. Dinheiro "fora de vista" é dinheiro "fora de gasto".\n\nCONFIGURE AGORA:\n• Valor: 10-20% da renda\n• Data: dia do pagamento\n• Destino: conta reserva separada\n\nEssa automação vai construir seu escudo enquanto você dorme.` },
        { title:'Capítulo 9: Protegendo o Que Construiu', content:`Depois de completar a reserva, o trabalho não acaba.\n\nCOMO MANTER A RESERVA SAUDÁVEL:\n\n1. NUNCA misture com outros objetivos\nCrie contas separadas para: reserva, férias, carro novo, reformas.\n\n2. ATUALIZE O VALOR PERIODICAMENTE\nSe seus gastos aumentaram (filho, mudança de cidade, novo plano de saúde), recalcule e ajuste a reserva.\n\n3. CONSIDERE A INFLAÇÃO\nR$18.000 de hoje valem menos que R$18.000 daqui a 5 anos. O Tesouro Selic automaticamente se atualiza — mas monitore.\n\n4. DIVERSIFIQUE OS BANCOS\nSe sua reserva passa de R$250k, distribua entre instituições (limite do FGC por banco).\n\n5. REVISE ANUALMENTE\n• Os valores ainda cobrem meus gastos atuais?\n• Meu perfil de risco mudou (virei autônomo, tive filho)?\n• Está rendendo acima do IPCA?\n\nA reserva de emergência não é um investimento para crescer — é um seguro para proteger.` },
        { title:'Capítulo 10: Próximos Passos', content:`Parabéns por chegar até aqui!\n\nSUA MISSÃO DOS PRÓXIMOS 6 MESES:\n\n📋 SEMANA 1:\n□ Calcule seus gastos essenciais mensais\n□ Defina sua meta (3, 6 ou 12 meses)\n□ Abra uma conta digital separada (Inter, Nubank, C6)\n\n💰 SEMANA 2:\n□ Faça o primeiro depósito (R$50, R$100, R$500 — o que puder)\n□ Configure transferência automática mensal\n□ Pesquise Tesouro Selic na sua corretora\n\n📈 MÊS 2-6:\n□ Contribua mensalmente sem falhar\n□ Adicione qualquer dinheiro extra (13º, PLR, venda)\n□ Acompanhe o crescimento no Munguba Finance\n□ Comemore cada R$1.000 atingido\n\n🎯 QUANDO A RESERVA ESTIVER COMPLETA:\n□ Mantenha as contribuições, mas direcione para investimentos\n□ Comece o módulo de Investimentos\n□ Continue educando-se financeiramente\n\n🌳 A reserva de emergência é a raiz da árvore financeira. Com raízes profundas, nenhuma tempestade derruba.` },
      ]
    }
  },
  {
    num:5, icon:'📈', title:'Primeiros Investimentos',
    desc:'Comece a fazer seu dinheiro trabalhar por você, do zero ao avançado.',
    topics:['Renda fixa vs variável','Tesouro Direto para iniciantes','FIIs: renda passiva mensal'],
    color:'#1D6FA4', bg:'#EFF6FF',
    book: {
      title:'Investimentos: Do Zero ao Primeiro Portfólio',
      pages: [
        { title:'Introdução', content:`Warren Buffett começou a investir aos 11 anos. Aos 30, tinha sua primeira fortuna.\n\nEle mesmo disse: "Se eu soubesse o que sei hoje, teria começado antes."\n\nVocê não precisa começar aos 11 anos. Mas precisa começar HOJE.\n\nEste módulo é seu guia completo do zero ao primeiro portfólio de investimentos. Sem jargão desnecessário, sem complexidade artificial — só o que você precisa saber para colocar seu dinheiro para trabalhar por você.` },
        { title:'Capítulo 1: Por Que Investir É Obrigatório', content:`"Mas eu prefiro guardar na poupança, é mais seguro."\n\nEssa frase está destruindo o patrimônio de milhões de brasileiros.\n\nA POUPANÇA vs INFLAÇÃO (últimos anos):\n• Poupança rendeu: ~6-7% ao ano\n• Inflação (IPCA): 5-12% ao ano\n• Resultado: poder de compra perdido\n\nO QUE ISSO SIGNIFICA NA PRÁTICA:\nR$10.000 guardados na poupança por 5 anos a 6% a.a. = R$13.382.\nMas se a inflação foi de 8% a.a., você precisaria de R$14.693 para ter o mesmo poder de compra.\n\nVocê "ganhou" R$3.382 e PERDEU R$1.311 em termos reais.\n\nA SOLUÇÃO:\nInvestir em ativos que rendem acima da inflação de forma consistente.\n\nREGRA DE OURO:\nSeu dinheiro deve trabalhar para você — não o contrário.` },
        { title:'Capítulo 2: Seu Perfil de Investidor', content:`Antes de escolher qualquer investimento, conheça seu perfil.\n\nOS 3 PERFIS:\n\n🟢 CONSERVADOR\n• Prioriza segurança absoluta\n• Aceita rendimentos menores\n• Não suporta ver o patrimônio oscilando\n• Portfólio: 80-100% renda fixa\n\n🟡 MODERADO\n• Equilíbrio entre segurança e retorno\n• Aceita pequenas oscilações\n• Horizonte de 3-7 anos\n• Portfólio: 50-70% renda fixa + 30-50% variável\n\n🔴 ARROJADO\n• Prioriza retorno máximo no longo prazo\n• Suporta grandes oscilações sem entrar em pânico\n• Horizonte de 10+ anos\n• Portfólio: 20-40% renda fixa + 60-80% variável\n\n⚠️ CUIDADO:\nMuitas pessoas descobrem que são conservadoras quando a bolsa cai 30% e vendem tudo no fundo — e depois compram no pico. Seja honesto consigo mesmo antes de investir.` },
        { title:'Capítulo 3: Renda Fixa na Prática', content:`Renda fixa = você sabe (ou tem previsibilidade de) quanto vai ganhar.\n\nOS PRINCIPAIS PRODUTOS:\n\n📌 TESOURO DIRETO\n• Tesouro Selic: para reserva (liquidez diária)\n• Tesouro IPCA+: protege da inflação (longo prazo)\n• Tesouro Prefixado: taxa travada (apostas em queda de juros)\n\n📌 CDB (Certificado de Depósito Bancário)\n• Emitido por bancos\n• 100% CDI em bancos grandes; 110-120% CDI em bancos menores\n• FGC garante até R$250k\n• Cuidado com liquidez — muitos só no vencimento\n\n📌 LCI e LCA\n• Isentos de IR para pessoa física\n• LCI: crédito imobiliário | LCA: agronegócio\n• Geralmente, prazo mínimo de 90 dias\n\n📌 DEBÊNTURES\n• Dívidas de empresas privadas\n• Risco maior que governo/bancos\n• Debêntures incentivadas: isentas de IR\n\n📌 CRI e CRA\n• Certificados imobiliários e do agronegócio\n• Isentos de IR\n• Risco depende do emissor` },
        { title:'Capítulo 4: Renda Variável para Iniciantes', content:`Renda variável = o retorno não é garantido. Mas o potencial é muito maior.\n\nO BÁSICO ANTES DE COMEÇAR:\n✅ Reserva de emergência completa\n✅ Zero dívidas caras\n✅ Horizonte de investimento de 5+ anos\n✅ Compreender que OSCILAÇÕES SÃO NORMAIS\n\nPOR ONDE COMEÇAR:\n\n1. ETFs (Exchange Traded Funds)\nFundos que replicam índices — a escolha mais inteligente para iniciantes.\n• BOVA11: replica o Ibovespa (as maiores empresas do Brasil)\n• IVVB11: replica o S&P 500 americano (as 500 maiores empresas dos EUA)\n• Vantagem: diversificação automática, baixo custo\n\n2. FIIs (Fundos Imobiliários)\nDividendos mensais isentos de IR. Cota a partir de R$10.\n• HGLG11, MXRF11, KNRI11\n\n3. AÇÕES\nComeçar com empresas sólidas e pagadoras de dividendos.\n• ITUB4, BBDC4, TAEE11, BBAS3\n\nNUNCA comece com derivativos, opções, mini contratos ou criptomoedas sem amplo conhecimento.` },
        { title:'Capítulo 5: Abrindo Conta em Corretora', content:`PASSO A PASSO COMPLETO:\n\n1. ESCOLHA A CORRETORA\nPara iniciantes, recomendo:\n• NuInvest (Nubank): simples, sem taxa\n• Rico: plataforma completa, sem taxa\n• XP Investimentos: maior variedade\n• BTG Pactual Digital: sólida, confiável\n\n2. FAÇA O CADASTRO (15 minutos)\n• CPF, RG, dados bancários\n• Comprovante de residência\n• Selfie para verificação\n\n3. FAÇA O SUITABILITY (perfil de investidor)\n• Questionário obrigatório pela CVM\n• Responda com honestidade\n• Determina quais produtos você pode acessar\n\n4. TRANSFIRA O DINHEIRO\n• Faça um TED ou PIX para a conta da corretora\n• O dinheiro fica disponível em minutos\n\n5. COMECE COM POUCO\n• Tesouro Selic a partir de R$30\n• ETFs a partir de 1 cota (~R$100)\n• FIIs a partir de 1 cota (~R$10 a R$200)\n\nIMPORTANTE: Corretoras são reguladas pela CVM e B3. Seu dinheiro em ações e FIIs é custodiado na B3, não na corretora — mesmo se a corretora falir, você não perde.` },
        { title:'Capítulo 6: Diversificação — A Regra de Ouro', content:`"Don't put all your eggs in one basket."\n— Provérbio inglês\n\nDiversificação é a única "mágica" gratuita do mercado financeiro — ela reduz risco sem necessariamente reduzir retorno.\n\nCOMO DIVERSIFICAR:\n\nPOR CLASSE DE ATIVO:\n• Renda fixa + renda variável\n• Ações + FIIs + ETFs\n\nPOR SETOR:\n• Não concentre em bancos apenas\n• Distribua: energia, saúde, varejo, commodities, tecnologia\n\nPOR GEOGRAFIA:\n• Brasil (BOVA11) + Internacional (IVVB11)\n\nPOR MOEDA:\n• Reais + dólar (via ETFs ou BDRs)\n\nO PORTFÓLIO INICIANTE (sugestão):\n• 50% Tesouro Selic (reserva e estabilidade)\n• 20% CDB/LCI (renda fixa extra)\n• 15% FIIs (renda passiva mensal)\n• 15% ETFs/Ações (crescimento longo prazo)\n\nAjuste conforme seu perfil e horizonte de tempo.` },
        { title:'Capítulo 7: Erros que Todo Iniciante Comete', content:`Aprender com os erros dos outros é muito mais barato.\n\n🚨 ERRO 1: TENTAR ACERTAR O TIMING\n"Vou esperar a bolsa cair para comprar." A pesquisa mostra que ninguém — nem os profissionais — consegue acertar o melhor momento. Invista regularmente (aportes mensais) independente do momento.\n\n🚨 ERRO 2: VENDER NO FUNDO DO POÇO\nBolsa caiu 30%? A reação errada é vender. A certa é comprar mais (se tiver reserva e horizonte longo). Grandes fortunas são feitas em crises.\n\n🚨 ERRO 3: SEGUIR DICAS DE INFLUENCER\n"Compre essa ação, vai dobrar!" Influenciadores financeiros podem ter conflito de interesse. Pesquise você mesmo ou consulte um analista certificado (CNPI).\n\n🚨 ERRO 4: CONCENTRAÇÃO EXCESSIVA\nPôr 80% do patrimônio em uma única ação. Empresas falidas existem (Americanas, OGX). Diversifique.\n\n🚨 ERRO 5: IGNORAR O IR\nAções, FIIs e renda fixa têm regras tributárias específicas. Ignorar pode gerar multas e dores de cabeça na declaração.\n\n🚨 ERRO 6: OLHAR O PORTFÓLIO TODO DIA\nQuem acompanha o preço das ações diariamente tende a tomar decisões piores. Defina sua estratégia e não fique verificando.` },
        { title:'Capítulo 8: Aporte Mensal — O Segredo dos Ricos', content:`Não importa se você tem R$100 ou R$10.000 para investir por mês.\n\nO QUE IMPORTA: a CONSISTÊNCIA do aporte mensal.\n\nA ESTRATÉGIA DO DOLLAR-COST AVERAGING (DCA):\nInvestir um valor fixo mensalmente, independente do preço.\n\nEXEMPLO COM AÇÕES:\nJaneiro: cota a R$10 → compra 10 cotas\nFevereiro: cota a R$5 → compra 20 cotas\nMarço: cota a R$8 → compra 12,5 cotas\n\nPreço médio: R$7,67 (menor que o primeiro preço!)\n\nVANTAGEM DO DCA:\n• Você automaticamente compra mais quando está barato\n• Elimina o estresse de tentar acertar o timing\n• Funciona mesmo sem conhecimento avançado\n\nO PODER DO LONGO PRAZO:\nR$300/mês a 10% a.a. por:\n• 10 anos: R$57.000 (investiu R$36.000)\n• 20 anos: R$189.000 (investiu R$72.000)\n• 30 anos: R$543.000 (investiu R$108.000)\n\nA maior parte do resultado vem do tempo, não do valor investido.` },
        { title:'Capítulo 9: Monitorando Seus Investimentos', content:`Investir bem é 20% escolher os ativos certos e 80% comportamento ao longo do tempo.\n\nCOMO MONITORAR SEM ENLOUQUECER:\n\nREVISÃO MENSAL (30 minutos):\n• Quanto investi no mês?\n• Qual o saldo total?\n• Alguma ação/FII divulgou resultado relevante?\n\nREVISÃO TRIMESTRAL (1 hora):\n• Meu portfólio está alinhado com minha estratégia?\n• Algum ativo precisa ser rebalanceado?\n• Meus objetivos mudaram?\n\nREVISÃO ANUAL (2-3 horas):\n• Qual foi meu retorno no ano?\n• Bati o IPCA? Bati o CDI?\n• Meu perfil de risco mudou?\n• Preciso ajustar a alocação?\n\nO QUE NÃO FAZER:\n❌ Verificar preços de ações diariamente\n❌ Vender toda vez que uma empresa divulga notícia ruim\n❌ Comparar seu portfólio com o de outra pessoa\n❌ Mudar de estratégia a cada mês\n\nConsistência e paciência superam inteligência no mercado financeiro.` },
        { title:'Capítulo 10: Seu Primeiro Portfólio', content:`Chegou a hora de colocar em prática.\n\n🎯 PORTFÓLIO INICIAL PARA R$500/mês:\n\nOpção Conservadora:\n• R$300 → Tesouro Selic (60%)\n• R$100 → CDB 100% CDI liquidez diária (20%)\n• R$100 → FIIs via ETF (HGRE11 ou similar) (20%)\n\nOpção Moderada:\n• R$200 → Tesouro Selic (40%)\n• R$150 → FIIs (HGLG11, MXRF11) (30%)\n• R$150 → ETF BOVA11 ou IVVB11 (30%)\n\nOpção Arrojada:\n• R$100 → Tesouro Selic (20%)\n• R$150 → FIIs (30%)\n• R$250 → ETFs e Ações (50%)\n\n📋 PLANO DE AÇÃO:\n□ Semana 1: Abrir conta em corretora\n□ Semana 2: Fazer primeiro aporte em Tesouro Selic\n□ Mês 2: Expandir para FIIs\n□ Mês 3: Iniciar em ETFs\n□ Mês 4+: Aportes mensais automáticos\n\n🌳 LEMBRE-SE:\nTodo investidor experiente foi um dia um iniciante nervoso. A diferença entre eles e você é apenas o tempo que passaram aplicando o conhecimento.\n\nComece hoje. Mesmo com pouco. O futuro agradece.` },
      ]
    }
  },
  {
    num:6, icon:'🗺️', title:'Planejamento de Longo Prazo',
    desc:'Trace o caminho para a independência financeira e aposentadoria tranquila.',
    topics:['Juros compostos na prática','PGBL vs VGBL','FIRE: liberdade financeira'],
    color:'#B45309', bg:'#FFFBEB',
    book: {
      title:'Independência Financeira: Seu Mapa do Tesouro',
      pages: [
        { title:'Introdução', content:`Independência financeira não é ser rico.\n\nÉ ter patrimônio suficiente para que seus investimentos gerem renda maior que seus gastos — para sempre.\n\nNesse ponto, trabalhar vira uma escolha, não uma obrigação.\n\nEste módulo é sobre o longo prazo: aposentadoria, independência financeira, planejamento sucessório e as estratégias que a maioria das pessoas só descobre quando já perdeu décadas.\n\nVamos começar pelo ativo mais valioso de todos: o tempo.` },
        { title:'Capítulo 1: A Máquina do Tempo Financeira', content:`O maior aliado do investidor não é o talento, a inteligência ou o capital. É o TEMPO.\n\nA REGRA DOS 72:\nDivida 72 pela taxa de retorno anual para saber em quantos anos seu dinheiro dobra.\n\nExemplos:\n• 6% a.a. (poupança): dobra em 12 anos\n• 10% a.a. (carteira diversificada): dobra em 7,2 anos\n• 15% a.a. (carteira arrojada): dobra em 4,8 anos\n\nO PODER DO INÍCIO PRECOCE:\n\nPessoa A começa aos 25: investe R$500/mês por 40 anos a 10% a.a.\nResultado: R$2.659.260\n\nPessoa B começa aos 35: investe R$1.000/mês por 30 anos a 10% a.a.\nResultado: R$2.167.000\n\nA Pessoa B investe O DOBRO por mês e ainda fica com R$492.260 a menos.\n\n10 anos de diferença = quase meio milhão a menos.\n\nA melhor hora para plantar uma árvore foi há 20 anos. A segunda melhor é hoje.` },
        { title:'Capítulo 2: Previdência Privada', content:`PGBL vs VGBL — a diferença que pode economizar dezenas de milhares de reais.\n\nPGBL (Plano Gerador de Benefício Livre):\n✅ Deduz até 12% da renda bruta no IR anual\n✅ Ideal para quem faz declaração completa\n✅ IR incide sobre todo o valor resgatado (principal + rendimento)\n🎯 Para quem tem: renda alta, faz declaração completa do IR\n\nVGBL (Vida Gerador de Benefício Livre):\n✅ Sem dedução no IR anual\n✅ IR incide apenas sobre os rendimentos\n✅ Ideal para declaração simplificada\n🎯 Para quem tem: renda mais baixa, declaração simplificada\n\nTABELAS DE IR NA PREVIDÊNCIA:\n\nProgressiva: alíquota aumenta conforme valor resgatado (mesmo IR regular)\nRegressiva: quanto mais tempo, menor a alíquota\n• Até 2 anos: 35%\n• 2-4 anos: 30%\n• 4-6 anos: 25%\n• 6-8 anos: 20%\n• 8-10 anos: 15%\n• Acima de 10 anos: 10%\n\nPara longo prazo (10+ anos), tabela regressiva com PGBL é uma das melhores estratégias de planejamento fiscal.` },
        { title:'Capítulo 3: FIRE — Independência Financeira', content:`FIRE = Financial Independence, Retire Early\n(Independência Financeira, Aposentadoria Antecipada)\n\nO PRINCÍPIO DO FIRE:\nAcumular patrimônio suficiente para viver dos rendimentos sem precisar trabalhar.\n\nA REGRA DOS 4%:\nPesquisa de William Bengen (1994): uma carteira diversificada pode sustentar retiradas de 4% ao ano indefinidamente.\n\nFórmula: Patrimônio necessário = Gastos anuais × 25\n\nEXEMPLOS:\n• Gastos de R$3.000/mês (R$36.000/ano) → precisa de R$900.000\n• Gastos de R$5.000/mês (R$60.000/ano) → precisa de R$1.500.000\n• Gastos de R$10.000/mês (R$120.000/ano) → precisa de R$3.000.000\n\nMODALIDADES DO FIRE:\n• Lean FIRE: vida muito frugal, patrimônio menor\n• Fat FIRE: manter estilo de vida confortável\n• Barista FIRE: trabalho de meio período para complementar\n• Coast FIRE: parar de aportar e deixar crescer até a aposentadoria\n\nO FIRE não é sobre parar de trabalhar. É sobre ter a escolha.` },
        { title:'Capítulo 4: Aposentadoria pelo INSS', content:`Antes de planejar a aposentadoria privada, entenda o INSS — e suas limitações.\n\nTETO DO INSS (2024): R$7.786,02\nMesmo que você ganhe R$20.000, receberá no máximo R$7.786.\n\nCOMO CALCULAR SUA APOSENTADORIA:\n• Média dos últimos 18 anos de salários\n• Multiplicado por alíquota baseada no tempo de contribuição\n\nA REALIDADE:\nA maioria dos brasileiros recebe 60-70% do teto do INSS na aposentadoria — o que raramente mantém o padrão de vida do período ativo.\n\nPOR QUE ISSO IMPORTA:\nSe você ganha R$10.000 hoje e quer manter esse padrão na aposentadoria, o INSS pode cobrir R$5.000-7.000. Os outros R$3.000-5.000 precisam vir do seu patrimônio.\n\nESSA É A LACUNA QUE OS INVESTIMENTOS PREENCHEM.\n\nIMPORTANTE: contribua corretamente para o INSS (não "se aposente" de forma irregular). O benefício é parte do planejamento, não o plano inteiro.` },
        { title:'Capítulo 5: Construindo Renda Passiva', content:`Renda passiva = dinheiro que entra enquanto você dorme, viaja, trabalha ou não faz nada.\n\nAS PRINCIPAIS FONTES:\n\n📊 DIVIDENDOS DE AÇÕES\nEmpresas sólidas distribuem lucros regularmente.\nExemplos: TAEE11 (~8% a.a.), ENGI11 (~7%), BBAS3 (~9%)\n\n🏢 DIVIDENDOS DE FIIs\nDistribuição mensal, isenta de IR.\nExemplos: HGLG11 (~9% a.a.), MXRF11 (~11%), KNRI11 (~8%)\n\n🏦 JUROS DE RENDA FIXA\nTesouro IPCA+, CDBs de longo prazo.\nRiscos menores, retorno previsível.\n\n🏠 RENDA DE IMÓVEIS\nAluguel de imóveis próprios ou via FIIs.\n\n💡 META DE RENDA PASSIVA:\nCalcule quanto você gasta por mês e trabalhe para que sua renda passiva cubra esse valor.\n\nEXEMPLO PRÁTICO:\nR$500k em FIIs com DY de 10% a.a. = R$50.000/ano = R$4.167/mês\n\nCom esse portfólio, você pode cobrir boa parte dos seus gastos mensais em dividendos isentos de IR.` },
        { title:'Capítulo 6: Planejamento Sucessório', content:`"Você se preocupa em construir patrimônio. Mas já pensou no que acontece com ele depois?"\n\nPLANEJAMENTO SUCESSÓRIO: garantir que seu patrimônio chegue para quem você quer, da forma que você quer, com o menor custo possível.\n\nSEM PLANEJAMENTO:\n• Inventário pode demorar 2 a 10 anos\n• Custos judiciais de 4% a 6% do patrimônio\n• Conflitos familiares\n• Família sem acesso ao dinheiro durante o processo\n\nFERRAMENTAS DE PLANEJAMENTO:\n\n📋 TESTAMENTO: registra sua vontade sobre a herança. Obrigatório para quem tem imóveis ou filhos de relacionamentos diferentes.\n\n🏛️ HOLDING FAMILIAR: empresa que concentra os bens da família, facilitando a gestão e a transmissão.\n\n🔄 DOAÇÃO EM VIDA: antecipar a herança com reserva de usufruto (você continua usando o bem enquanto vive).\n\n💰 SEGURO DE VIDA: liquidez imediata para a família no momento do sinistro.\n\n📜 PREVIDÊNCIA PRIVADA: não entra em inventário — herdeiros recebem diretamente.` },
        { title:'Capítulo 7: Simulações de Independência', content:`Números reais para objetivos reais.\n\nCENÁRIO 1: APOSENTADORIA AOS 60\nIdade atual: 30 anos\nTempo: 30 anos\nAporte mensal: R$800\nRetorno médio: 10% a.a.\nPatrimônio acumulado: R$1.885.000\nRenda passiva (4%): R$75.400/ano = R$6.283/mês\n\nCENÁRIO 2: INDEPENDÊNCIA FINANCEIRA AOS 45\nIdade atual: 30 anos\nTempo: 15 anos\nAporte mensal: R$3.000\nRetorno médio: 12% a.a.\nPatrimônio acumulado: R$1.490.000\nRenda passiva (4%): R$59.600/ano = R$4.967/mês\n\nCENÁRIO 3: COAST FIRE AOS 50\nInveste pesado dos 30 aos 40 (R$2.000/mês a 10%)\nAcumula R$410.000\nPara os aportes e deixa crescer por mais 10 anos\nAos 50 tem: R$1.064.000\nRenda passiva: R$42.560/ano = R$3.547/mês\n\n💡 CONCLUSÃO:\nHá múltiplos caminhos. O importante é escolher um e começar.` },
        { title:'Capítulo 8: Inflação e Longevidade', content:`Dois inimigos silenciosos do planejamento de longo prazo.\n\nA INFLAÇÃO:\nR$5.000 de hoje não vai comprar as mesmas coisas daqui a 20 anos.\n\nCOM INFLAÇÃO DE 5% A.A.:\nO que custa R$5.000 hoje custará:\n• Em 10 anos: R$8.144\n• Em 20 anos: R$13.267\n• Em 30 anos: R$21.610\n\nPOR ISSO seus investimentos precisam render ACIMA do IPCA:\n✅ Tesouro IPCA+: garante retorno real acima da inflação\n✅ FIIs: contratos de aluguel corrigidos pelo IGPM/IPCA\n✅ Ações: empresas repassam inflação para preços\n\nA LONGEVIDADE:\nBrasileiros vivem em média 76 anos. Mas isso é a média — muitos vivem 90+.\n\nPLANEJE PARA VIVER MUITO:\nSe você se aposentar aos 60 e viver até 90, precisará de 30 anos de renda passiva.\n\nA REGRA DOS 4% JÁ CONSIDERA ISSO:\nCarteiras diversificadas sustentam retiradas de 4% por 30+ anos sem se esgotar — mas revise periodicamente.` },
        { title:'Capítulo 9: Revisando o Plano ao Longo da Vida', content:`Um plano financeiro de longo prazo não é estático — ele evolui com você.\n\nOS GATILHOS DE REVISÃO:\n\n👶 FILHO: recalcule gastos, aumente reserva, revise seguro de vida, crie investimento educacional\n\n💒 CASAMENTO: consolide planejamentos, defina regime de bens, revise testamento\n\n🏠 COMPRA DE IMÓVEL: impacta fluxo de caixa por 20-30 anos, muda o portfólio\n\n💼 MUDANÇA DE EMPREGO: ajuste contribuições ao INSS, revise previdência privada\n\n👴 CHEGANDO NA APOSENTADORIA: gradualmente migre de crescimento para renda (mais FIIs e renda fixa, menos ações de crescimento)\n\nA REVISÃO ANUAL COMPLETA:\n✅ Quanto acumulei este ano?\n✅ Estou no ritmo para atingir minha meta?\n✅ Minha alocação ainda reflete meus objetivos?\n✅ Minha situação de vida mudou?\n✅ Preciso ajustar seguros e beneficiários?\n\nO plano não é a realidade — é um mapa que você atualiza conforme o terreno muda.` },
        { title:'Capítulo 10: Sua Declaração de Independência', content:`Chegou o momento de transformar conhecimento em compromisso.\n\nSUAS METAS DE LONGO PRAZO (escreva as suas):\n\n🎯 META 5 ANOS:\nExemplo: "Ter R$150.000 investidos e reserva completa de 6 meses"\n\n🎯 META 10 ANOS:\nExemplo: "Ter R$500.000 em renda passiva cobrindo 50% dos meus gastos"\n\n🎯 META 20 ANOS:\nExemplo: "Ser financeiramente independente com renda passiva de R$8.000/mês"\n\nSEU PLANO DE AÇÃO IMEDIATO:\n□ Calcule seu número FIRE (gastos mensais × 12 × 25)\n□ Simule quanto precisa aportar mensalmente\n□ Configure aportes automáticos\n□ Defina revisão anual no calendário\n□ Se tiver filhos, revise seu seguro de vida\n□ Pesquise PGBL/VGBL se paga muito IR\n\n🌳 A MENSAGEM FINAL:\nA independência financeira não é um destino reservado para pessoas especiais.\n\nÉ o resultado inevitável de decisões corretas, repetidas consistentemente, ao longo do tempo.\n\nVocê já deu o primeiro passo ao estar aqui.\nO próximo passo é o mais importante: começar.` },
      ]
    }
  },
  {
    num:7, icon:'🏢', title:'Empreendedorismo Financeiro',
    desc:'Gerencie as finanças do seu negócio com profissionalismo e clareza.',
    topics:['Separar PF de PJ','Fluxo de caixa empresarial','Simples Nacional e impostos'],
    color:'#D97706', bg:'#FFF7ED',
    book: {
      title:'Finanças Empresariais: Do Caos à Clareza',
      pages: [
        { title:'Introdução', content:`A maioria dos negócios não fecha por falta de clientes.\n\nFecha por falta de gestão financeira.\n\nEmpreender é um dos atos de coragem mais altos que existe. Mas coragem sem controle financeiro é um tiro no escuro.\n\nEste módulo é para quem já tem — ou quer ter — seu próprio negócio. Vamos trabalhar com as ferramentas que separam os negócios que prosperam dos que fecham nos primeiros 2 anos.` },
        { title:'Capítulo 1: PF vs PJ — A Separação Sagrada', content:`O erro mais comum do empreendedor brasileiro: misturar dinheiro pessoal com empresarial.\n\nO QUE ACONTECE QUANDO VOCÊ MISTURA:\n• Você não sabe se o negócio dá lucro de verdade\n• Dificulta o cálculo de impostos\n• Complica o relacionamento com fornecedores e bancos\n• Risco de "comer" o capital de giro\n• Problemas na declaração do IR\n\nCOMO SEPARAR CORRETAMENTE:\n\n1. CONTA BANCÁRIA PJ\nAbra uma conta exclusiva para o negócio. Gratuita: Nubank PJ, Mercado Pago, Inter PJ.\n\n2. PRÓ-LABORE FIXO\nDefina um "salário" mensal para você — e só isso pode ir para sua conta pessoal. Não retire mais que o definido.\n\n3. CARTÃO CORPORATIVO\nPara despesas da empresa. Zero mistura com despesas pessoais.\n\n4. SISTEMA DE GESTÃO\nQualquer sistema (planilha, app) que registre entradas e saídas da empresa separadamente.\n\nO PRÓ-LABORE IDEAL:\n20-30% do faturamento, ajustado conforme crescimento do negócio.` },
        { title:'Capítulo 2: DRE Simplificada', content:`DRE = Demonstração do Resultado do Exercício\n\nÉ a radiografia financeira do seu negócio. Em uma página, você vê se está ganhando ou perdendo dinheiro.\n\nESTRUTURA SIMPLIFICADA:\n\n(+) RECEITA BRUTA: tudo que o negócio faturou\n(-) DEDUÇÕES: impostos sobre faturamento (Simples, ICMS, ISS)\n(=) RECEITA LÍQUIDA\n\n(-) CUSTOS: o que você gasta para entregar o produto/serviço\n(=) LUCRO BRUTO\n\n(-) DESPESAS OPERACIONAIS: aluguel, salários, energia, marketing\n(=) EBITDA (lucro antes de juros, impostos, depreciação)\n\n(-) DEPRECIAÇÃO E AMORTIZAÇÃO\n(-) JUROS (empréstimos)\n(=) LUCRO ANTES DO IR\n\n(-) IMPOSTO DE RENDA\n(=) LUCRO LÍQUIDO\n\nEXEMPLO REAL (farmácia):\nFaturamento: R$50.000\n(-) Simples Nacional 6%: R$3.000\n(-) Custo produtos (CMV 40%): R$20.000\n(-) Despesas fixas: R$15.000\n(=) Lucro líquido: R$12.000 (24% de margem)` },
        { title:'Capítulo 3: Fluxo de Caixa Empresarial', content:`"Empresa lucrativa pode falir por falta de caixa."\n\nIsso parece absurdo, mas acontece o tempo todo.\n\nEXEMPLO:\nVocê vende R$100.000 em um mês, mas recebe 60 dias depois.\nMas paga fornecedores em 30 dias.\nVocê tem lucro no papel e não tem dinheiro no caixa.\n\nFLUXO DE CAIXA vs DRE:\n• DRE: mostra se você tem lucro (competência)\n• Fluxo de caixa: mostra se você tem dinheiro (caixa)\n\nMONITORE DIARIAMENTE:\n• Saldo do dia\n• Entradas previstas (recebimentos)\n• Saídas previstas (pagamentos)\n• Saldo projetado\n\nINDICADORES CRÍTICOS:\n\nCICLO DE CAIXA:\nPrazo de recebimento - Prazo de pagamento de fornecedores\nIdeal: número NEGATIVO (você recebe antes de pagar)\n\nPRAZO MÉDIO DE RECEBIMENTO:\nQuantos dias em média o cliente demora para pagar\n\nPRAZO MÉDIO DE PAGAMENTO:\nQuantos dias você tem para pagar os fornecedores\n\nCAPITAL DE GIRO:\nO dinheiro que sustenta a operação entre pagar fornecedores e receber clientes.` },
        { title:'Capítulo 4: Simples Nacional', content:`O Simples Nacional é o regime tributário mais comum entre pequenas empresas.\n\nQUEM PODE USAR:\n• MEI: faturamento até R$81.000/ano (2024)\n• ME: faturamento até R$360.000/ano\n• EPP: faturamento até R$4.800.000/ano\n\nCOMO FUNCIONA:\nUm único boleto mensal (DAS) recolhe 8 impostos: IRPJ, CSLL, PIS, COFINS, IPI, ICMS, ISS e CPP.\n\nANEXOS E ALÍQUOTAS:\n• Anexo I (Comércio): 4% a 19%\n• Anexo II (Indústria): 4,5% a 30%\n• Anexo III (Serviços como consultoria, TI): 6% a 33%\n• Anexo IV (Serviços como construção): 4,5% a 33%\n• Anexo V (Serviços de alta tecnologia): 15,5% a 30%\n\nO SIMPLES SEMPRE COMPENSA?\nNÃO. Para algumas situações, Lucro Presumido ou Real pode ser mais vantajoso.\n\nVALIDE COM CONTADOR:\nSe fatura mais de R$300.000/ano, faça uma simulação comparando regimes tributários. A diferença pode ser de dezenas de milhares de reais por ano.` },
        { title:'Capítulo 5: Precificação Correta', content:`O maior erro de empresas iniciantes: precificar por "feeling" ou copiar o concorrente.\n\nO MÉTODO DO MARKUP:\n\nMarkup = Preço de venda ÷ Custo do produto\n\nPASSO A PASSO:\n1. Identifique o Custo do Produto (CP): R$30\n2. Estime as despesas fixas mensais: R$8.000\n3. Estime o volume de vendas mensal: 200 unidades\n4. Rateie as fixas: R$8.000 ÷ 200 = R$40 por produto\n5. Some impostos (ex: 8% do Simples): R$6,24\n6. Defina a margem de lucro desejada: 20%\n\nPreço = (CP + Despesa rateada) ÷ (1 - impostos - margem)\nPreço = (30 + 40) ÷ (1 - 0,08 - 0,20)\nPreço = 70 ÷ 0,72 = R$97,22\n\nVENDA ABAIXO DESSE VALOR = PREJUÍZO.\n\nO PONTO DE EQUILÍBRIO:\nFaturamento mínimo para cobrir todos os custos e despesas.\nPE = Despesas fixas ÷ Margem de contribuição\n\nConhecer seu ponto de equilíbrio é saber quando você começa a lucrar de verdade.` },
        { title:'Capítulo 6: Capital de Giro', content:`Capital de giro é o combustível que mantém o negócio funcionando.\n\nO QUE É:\nDinheiro necessário para financiar o ciclo operacional — pagar fornecedores, salários e despesas antes de receber dos clientes.\n\nCOMO CALCULAR:\nCapital de giro necessário = (Prazo médio de recebimento - Prazo médio de pagamento) × Faturamento diário\n\nEXEMPLO:\nFaturamento mensal: R$100.000 (R$3.333/dia)\nRecebe em: 45 dias\nPaga em: 15 dias\nDiferença: 30 dias\nCapital de giro necessário: 30 × R$3.333 = R$100.000\n\nCOMO MELHORAR O CAPITAL DE GIRO:\n✅ Reduza o prazo de recebimento (ofereça desconto para pagamento à vista)\n✅ Aumente o prazo com fornecedores (negocie prazos maiores)\n✅ Reduza estoques (compre o necessário, não em excesso)\n✅ Tenha uma linha de crédito reservada para emergências\n\nFONTES DE CAPITAL DE GIRO:\n• Lucro retido no negócio\n• Capital dos sócios\n• Antecipação de recebíveis\n• Empréstimo capital de giro bancário (última opção)` },
        { title:'Capítulo 7: Gestão de Estoque', content:`Estoque é dinheiro parado. Muito pouco ou muito tem custos diferentes.\n\nCUSTO DO ESTOQUE EXCESSIVO:\n• Capital de giro comprometido\n• Risco de obsolescência/vencimento\n• Custo de armazenamento\n• Ocupação de espaço físico\n\nCUSTO DO ESTOQUE INSUFICIENTE:\n• Perda de venda\n• Cliente insatisfeito\n• Compra emergencial com custo maior\n\nMÉTODOS DE GESTÃO:\n\n📊 CURVA ABC:\n• A (20% dos itens = 80% do faturamento): gestão rígida, reposição automática\n• B (30% dos itens = 15% do faturamento): gestão padrão\n• C (50% dos itens = 5% do faturamento): gestão simples, estoque mínimo\n\n📦 ESTOQUE MÍNIMO:\nQuantidade que garante o atendimento enquanto aguarda o reabastecimento.\n\n📦 PONTO DE PEDIDO:\nQuantidade que indica: hora de fazer novo pedido.\n\nPara o Munguba Finance (farmácia):\nControle rigoroso de validade, giro rápido de produtos de maior saída, estoque mínimo de medicamentos de uso contínuo.` },
        { title:'Capítulo 8: Indicadores de Performance', content:`"O que não é medido não pode ser melhorado."\n— Peter Drucker\n\nOS KPIs ESSENCIAIS DO NEGÓCIO:\n\n📊 MARGEM BRUTA\n= (Faturamento - Custo dos produtos) ÷ Faturamento × 100\nReferência: varia por setor. Varejo: 30-50%. Serviços: 50-80%.\n\n📊 MARGEM LÍQUIDA\n= Lucro líquido ÷ Faturamento × 100\nReferência: acima de 10% é saudável.\n\n📊 TICKET MÉDIO\n= Faturamento ÷ Número de vendas\nMeta: aumentar sem aumentar clientes\n\n📊 CUSTO DE AQUISIÇÃO DE CLIENTE (CAC)\n= Investimento em marketing ÷ Novos clientes gerados\nMeta: menor que o LTV do cliente\n\n📊 LIFETIME VALUE (LTV)\n= Ticket médio × Frequência de compra × Tempo de retenção\nMeta: LTV / CAC > 3\n\n📊 INADIMPLÊNCIA\n= (Valores em atraso ÷ Faturamento total) × 100\nReferência: abaixo de 3% é saudável\n\nMonitore mensalmente. O que você mede, você melhora.` },
        { title:'Capítulo 9: Crescendo com Saúde Financeira', content:`Crescimento sem controle financeiro é o caminho mais rápido para a falência.\n\nOS 3 PILARES DO CRESCIMENTO SAUDÁVEL:\n\n1. CAIXA ANTES DE CRESCIMENTO\nNunca expanda sem ter reserva de capital de giro para sustentar o crescimento.\n\n2. MARGENS MANTIDAS\nVender mais com margens menores pode ser pior que vender menos com margens maiores.\n\n3. TIME CERTO\nContrate quando a operação atual não consegue mais crescer sem ajuda — não antes.\n\nERROS FATAIS NO CRESCIMENTO:\n❌ Alugar espaço maior antes de ter demanda\n❌ Contratar equipe sem ter receita para pagar\n❌ Pegar empréstimo para crescer sem projeção clara de retorno\n❌ Abrir nova unidade antes da primeira ser rentável\n❌ Ignorar o fluxo de caixa durante expansão\n\nA REGRA DO CRESCIMENTO SUSTENTÁVEL:\nCresça no ritmo que seu caixa permite — não no ritmo que seu ego quer.\n\nEmpresas que crescem rápido demais frequentemente morrem de sucesso.` },
        { title:'Capítulo 10: Construindo um Negócio que Dura', content:`Um negócio sustentável é aquele que funciona sem você.\n\nOS 4 SISTEMAS DO NEGÓCIO DURADOURO:\n\n1. SISTEMA FINANCEIRO\n✅ DRE mensal automatizado\n✅ Fluxo de caixa diário monitorado\n✅ Reserva de 3-6 meses de custos fixos\n✅ Separação total PF/PJ\n\n2. SISTEMA OPERACIONAL\n✅ Processos documentados\n✅ Treinamento padronizado\n✅ Qualidade consistente sem depender do fundador\n\n3. SISTEMA COMERCIAL\n✅ Geração previsível de leads\n✅ Processo de vendas documentado\n✅ Gestão de clientes (CRM)\n\n4. SISTEMA DE GESTÃO\n✅ KPIs monitorados mensalmente\n✅ Reuniões de resultado periódicas\n✅ Planejamento anual formal\n\nSEU PLANO DE AÇÃO:\n□ Esta semana: separar conta PJ\n□ Este mês: fazer DRE do último mês\n□ Próximo trimestre: implementar controle de fluxo de caixa\n□ Este ano: revisão do regime tributário com contador\n\n🌳 O negócio é a árvore. A saúde financeira é o solo. Sem solo fértil, nenhuma árvore sobrevive.` },
      ]
    }
  },
  {
    num:8, icon:'💰', title:'Investimentos: Do Zero ao Profissional',
    desc:'Da primeira aplicação à carteira diversificada de um investidor experiente.',
    topics:['Análise fundamentalista','Análise técnica','Carteira de dividendos','Opções e derivativos'],
    color:'#059669', bg:'#ECFDF5',
    book: {
      title:'Investidor Profissional: Estratégias Avançadas',
      pages: [
        { title:'Introdução', content:`Há uma diferença enorme entre o investidor iniciante e o profissional.\n\nNão é o capital. Não é a inteligência. É o PROCESSO.\n\nInvestidores profissionais têm critérios claros para comprar, vender e manter. Têm controle emocional. Têm visão de longo prazo. E, acima de tudo, têm educação financeira contínua.\n\nEste módulo é o mais avançado do Munguba Finance. Aqui você vai aprender o que diferencia o investidor amador do profissional — e como você pode cruzar essa linha.` },
        { title:'Capítulo 1: Análise Fundamentalista', content:`A análise fundamentalista busca o VALOR INTRÍNSECO de uma empresa — quanto ela realmente vale, independente do preço de mercado.\n\nPIONEIROS: Benjamin Graham (O Pai do Value Investing) e Warren Buffett.\n\nCONCEITO CENTRAL:\nSe você descobrir que uma empresa vale R$100 e o mercado a está vendendo por R$60, você encontrou uma ação "com desconto". Compre e aguarde o mercado reconhecer o valor real.\n\nINDICADORES FUNDAMENTALISTAS:\n\nP/L (Preço/Lucro): quanto você paga por R$1 de lucro\n• P/L < 10: potencialmente barata\n• P/L > 30: potencialmente cara\n\nP/VP (Preço/Valor Patrimonial): compara preço com patrimônio contábil\n• P/VP < 1: empresa vale menos que seus ativos\n\nROE (Return on Equity): eficiência no uso do capital dos acionistas\n• ROE > 15%: eficiente\n\nDÍVIDA LÍQUIDA/EBITDA: quanto tempo levaria para pagar a dívida com o lucro operacional\n• < 2x: saudável\n• > 4x: atenção\n\nDIVIDEND YIELD: dividendos ÷ preço da ação\n• > 5% a.a.: boa pagadora de dividendos` },
        { title:'Capítulo 2: Análise Técnica', content:`Enquanto a análise fundamentalista olha para O QUE comprar, a análise técnica tenta determinar QUANDO comprar e vender.\n\nO PRINCÍPIO:\nTodo o histórico de preços e volumes já "reflete" as informações disponíveis. Os padrões gráficos tendem a se repetir.\n\nFERRAMENTAS PRINCIPAIS:\n\n📈 MÉDIAS MÓVEIS\n• Média dos últimos N preços de fechamento\n• Cruzamento de médias = sinal de compra/venda\n• MA20 cruzando MA50 para cima = sinal de compra\n\n📊 RSI (Relative Strength Index)\n• Oscilador de 0 a 100\n• Acima de 70: ativo sobrecomprado (possível queda)\n• Abaixo de 30: ativo sobrevendido (possível alta)\n\n📉 SUPORTE E RESISTÊNCIA\n• Suporte: nível de preço onde há muita demanda\n• Resistência: nível onde há muita oferta\n• Rompimento = mudança de tendência\n\n🕯️ CANDLESTICKS\n• Padrões de velas japonesas indicam tendências\n• Doji, Martelo, Engolfo de Alta/Baixa\n\n⚠️ CUIDADO:\nAnálise técnica funciona melhor combinada com fundamentalista. Use o fundamento para escolher O QUE, e a técnica para escolher QUANDO.` },
        { title:'Capítulo 3: Carteira de Dividendos', content:`A estratégia de dividendos é uma das mais conservadoras e eficazes para construir renda passiva no longo prazo.\n\nO PRINCÍPIO:\nInvestir em empresas que distribuem lucros regularmente e reinvestir esses dividendos para aumentar a posição.\n\nO EFEITO BOLA DE NEVE DOS DIVIDENDOS:\nVocê recebe dividendos → compra mais ações → recebe mais dividendos → compra mais ações...\n\nCARACTERÍSTICAS DAS MELHORES PAGADORAS:\n✅ Histórico de pelo menos 5 anos de dividendos consistentes\n✅ Payout ratio entre 40-70% (distribui parte, retém para crescer)\n✅ ROE acima de 15%\n✅ Dívida controlada\n✅ Setor estável (energia, bancos, utilities, seguros)\n\nEXEMPLOS CLÁSSICOS BRASIL:\n• Bancos: ITUB4, BBDC4, BBAS3, SANB11\n• Energia: TAEE11, ENGI11, CPFE3, TRPL4\n• Seguros: BBSE3, PSSA3\n• Saneamento: SAPR11, SBSP3\n\nO Barômetro de Dividendos:\nDY > 6% + ROE > 15% + Payout < 70% = candidato sólido para análise` },
        { title:'Capítulo 4: ETFs — A Estratégia do Nobel', content:`Daniel Kahneman, Prêmio Nobel de Economia, investe em fundos de índice (ETFs).\n\nJohn Bogle, fundador da Vanguard, demonstrou matematicamente que a maioria dos gestores profissionais NÃO bate o índice no longo prazo.\n\nPOR QUE ETFs SÃO TÃO EFICIENTES:\n• Taxa de administração baixíssima (~0,2% vs 2% de fundos ativos)\n• Diversificação automática de centenas de empresas\n• Sem risco de escolher a empresa errada\n• Transparência total (você sabe exatamente o que tem)\n• Simplicidade — investe uma vez, diversifica automaticamente\n\nOS PRINCIPAIS ETFs BRASILEIROS:\n\n🇧🇷 BOVA11: replica o Ibovespa (78 empresas maiores da B3)\n🌎 IVVB11: replica o S&P 500 americano (500 maiores empresas dos EUA)\n🏦 BBOV11: Ibovespa do BTG\n📊 SMAL11: small caps brasileiras (empresas menores com maior potencial)\n🏢 KNRI11 (não ETF): FII de tijolo diversificado\n\nA ESTRATÉGIA MAIS SIMPLES E EFICAZ:\n50% IVVB11 (exposição EUA/dólar)\n50% BOVA11 ou ações selecionadas (Brasil)\n\nAportes mensais, sem olhar o preço. 10-15 anos de consistência.` },
        { title:'Capítulo 5: Renda Fixa Avançada', content:`Para além do CDB básico, a renda fixa oferece produtos sofisticados com excelentes retornos.\n\nTESOURO IPCA+ COM JUROS SEMESTRAIS:\nVocê recebe os juros duas vezes por ano, não só no vencimento. Ideal para quem quer renda semestral preservada da inflação.\n\nDEBÊNTURES INCENTIVADAS:\nDívidas de empresas para financiar infraestrutura — ISENTAS de IR para pessoa física. Retornos de IPCA + 6-8% a.a. — superiores ao Tesouro IPCA+ com isenção fiscal.\n\nCRI e CRA PREMIUM:\nCertificados Imobiliários e do Agronegócio de empresas sólidas. Isentos de IR, frequentemente oferecem spreads superiores.\n\nCDB DE BANCO MENOR:\nBancos menores (fora do top 5) oferecem 110-120% do CDI com FGC. Rico em retorno, mas atenção ao limite garantido (R$250k).\n\nA ESTRATÉGIA DE ESCADINHA (Laddering):\nDistribua investimentos em vencimentos diferentes (1, 2, 3, 5 anos) para sempre ter dinheiro chegando — especialmente em momentos de alta de juros.\n\nO IMPOSTO OTIMIZADO:\nMantenha aplicações por mais de 720 dias para pagar 15% de IR (em vez de 22,5% de curto prazo). A diferença em grandes volumes é significativa.` },
        { title:'Capítulo 6: BDRs — Investindo no Exterior', content:`BDR = Brazilian Depositary Receipt\nCertificados que representam ações de empresas estrangeiras negociadas na B3.\n\nEXEMPLOS:\n• AAPL34 (Apple) — a maior empresa do mundo\n• AMZO34 (Amazon)\n• GOOGL34 (Alphabet/Google)\n• MSFT34 (Microsoft)\n• NFLX34 (Netflix)\n• TSLA34 (Tesla)\n\nVANTAGENS:\n✅ Exposição a empresas globais de tecnologia\n✅ Diversificação em dólar sem abrir conta no exterior\n✅ Negociados na B3 (mesmo processo que ações)\n\nDESVANTAGENS:\n❌ IR de 15% sobre ganho de capital (sem isenção dos R$20k/mês)\n❌ Câmbio influencia o retorno em reais\n❌ Menor liquidez que ETFs como IVVB11\n\nALTERNATIVA MAIS EFICIENTE:\nPara a maioria dos investidores, o IVVB11 é mais eficiente que comprar BDRs individuais — mesma exposição, melhor diversificação, processo mais simples.\n\nBDRs fazem sentido para investidores que querem exposição específica a determinadas empresas estrangeiras.` },
        { title:'Capítulo 7: Opções — O Básico do Avançado', content:`Opções são um dos instrumentos mais poderosos — e perigosos — do mercado financeiro.\n\nO QUE SÃO:\nContratos que dão o DIREITO (não a obrigação) de comprar ou vender um ativo por um preço determinado até uma data.\n\nTIPOS:\n📈 CALL (Opção de Compra): direito de COMPRAR o ativo ao preço de exercício\n📉 PUT (Opção de Venda): direito de VENDER o ativo ao preço de exercício\n\nSTRATÉGIAS CONSERVADORAS (para iniciantes em opções):\n\n🛡️ COMPRA DE PUT (Seguro de carteira):\nVocê tem ações e compra uma PUT como "seguro". Se as ações caírem, a PUT se valoriza e compensa a perda.\n\n💰 VENDA COBERTA DE CALL:\nVocê já tem as ações e VENDE uma CALL, recebendo um prêmio. Se a ação não subir acima do exercício, você fica com o prêmio. Gera "renda" extra sobre posições existentes.\n\n⚠️ ATENÇÃO:\nOpções têm data de vencimento — podem perder TODO o valor. Nunca use mais de 5% da carteira em opções especulativas. Estude profundamente antes de operar.` },
        { title:'Capítulo 8: Psicologia do Investidor Profissional', content:`O maior inimigo do investidor não é o mercado. É o próprio investidor.\n\nOS 5 COMPORTAMENTOS DO PROFISSIONAL:\n\n1. PROCESSO SOBRE RESULTADO\nUma decisão ruim pode gerar bom resultado por sorte. Uma boa decisão pode gerar resultado ruim por azar. O profissional julga pelo processo, não pelo resultado de curto prazo.\n\n2. SEPARAÇÃO EMOCIONAL\nO preço da ação não define o valor da empresa. A queda de 30% não significa que a empresa ficou 30% pior — pode ser oportunidade de compra.\n\n3. DIÁRIO DE INVESTIMENTOS\nRegistre cada decisão: por que comprou, por que vendeu, o que esperava. Revise periodicamente. Aprenda com os erros.\n\n4. CIRCLE OF COMPETENCE (Warren Buffett)\nInvista apenas no que você entende. Se não consegue explicar o negócio em 2 minutos, não invista.\n\n5. PENSAMENTO DE LONGO PRAZO\nBen Graham: "No curto prazo, o mercado é uma máquina de votar. No longo prazo, é uma máquina de pesar."\n\nO TESTE DO SONO:\nSe você vai dormir preocupado com um investimento, ele é grande demais para seu perfil ou você não entende suficientemente o ativo.` },
        { title:'Capítulo 9: Construindo Sua Carteira Profissional', content:`Uma carteira profissional não é um conjunto aleatório de ativos — é uma estrutura coerente com objetivos claros.\n\nO MODELO DOS 4 PILARES:\n\nPILAR 1 — RESERVA (10-20%)\n• Tesouro Selic ou CDB liquidez diária\n• Nunca invista sem esse colchão\n\nPILAR 2 — RENDA FIXA (20-40%)\n• Tesouro IPCA+ 2035 ou 2040\n• Debêntures incentivadas\n• LCI/LCA de médio prazo\n\nPILAR 3 — RENDA PASSIVA (20-30%)\n• FIIs de tijolo diversificados (KNRI11, HGLG11)\n• FIIs de papel (MXRF11, KNCR11)\n• Ações pagadoras de dividendos (TAEE11, BBSE3)\n\nPILAR 4 — CRESCIMENTO (20-40%)\n• ETFs (BOVA11, IVVB11)\n• Ações de crescimento (setor tech, saúde, consumo)\n• BDRs de empresas globais\n\nREBALANCEAMENTO:\nAnualmente, ajuste a carteira para a alocação alvo. Isso automaticamente faz você "vender caro e comprar barato".` },
        { title:'Capítulo 10: O Caminho Contínuo', content:`"O investimento no conhecimento rende os melhores juros."\n— Benjamin Franklin\n\nVocê chegou ao módulo mais avançado do Munguba Finance. Mas o aprendizado nunca para.\n\nSUA BIBLIOTECA ESSENCIAL:\n📚 "A Psicologia do Dinheiro" — Morgan Housel\n📚 "O Investidor Inteligente" — Benjamin Graham\n📚 "Ações Comuns, Lucros Extraordinários" — Philip Fisher\n📚 "De Zero a Um" — Peter Thiel\n📚 "Pai Rico, Pai Pobre" — Robert Kiyosaki\n📚 "Faça Fortuna com Ações" — Décio Bazin\n\nCOMUNIDADES E RECURSOS:\n🌐 Status Invest (análise de ações/FIIs)\n🌐 Funds Explorer (FIIs)\n🌐 Comparador Tesouro (renda fixa)\n🌐 B3.com.br (dados oficiais)\n\nSEU COMPROMISSO:\n□ 1 hora de estudo por semana sobre mercado financeiro\n□ Revisão trimestral da carteira\n□ 1 livro de finanças por trimestre\n□ Acompanhe resultados das empresas que investe\n□ Mantenha o Munguba Finance sempre atualizado\n\n🌳 A Munguba Finance não é apenas um app. É o começo de uma jornada.\n\nSua jornada para a liberdade financeira começa aqui e não tem fim.` },
      ]
    }
  },
]

export default function EducationScreen() {
  const [openBook, setOpenBook] = useState(null)
  const [page, setPage] = useState(0)

  if (openBook !== null) {
    const mod = MODULES[openBook]
    const book = mod.book
    const currentPage = book.pages[page]
    return (
      <div style={{ animation:'vIn .26s ease', maxWidth:800, margin:'0 auto' }}>
        {/* Book header */}
        <div style={{ background:`linear-gradient(135deg,${mod.color}dd,${mod.color})`, borderRadius:24, padding:'24px 28px', color:'#fff', marginBottom:20, position:'relative', overflow:'hidden' }}>
          <div style={{ position:'absolute', top:-20, right:-20, width:120, height:120, borderRadius:'50%', background:'rgba(255,255,255,.08)' }}/>
          <button onClick={() => { setOpenBook(null); setPage(0) }} style={{ background:'rgba(255,255,255,.2)', border:'none', color:'#fff', borderRadius:10, padding:'7px 14px', cursor:'pointer', fontFamily:'Outfit,sans-serif', fontSize:12, fontWeight:600, marginBottom:14 }}>
            ← Voltar aos módulos
          </button>
          <div style={{ fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'.14em', opacity:.7, marginBottom:6 }}>Módulo {mod.num} — Minilivro</div>
          <div style={{ fontSize:20, fontWeight:800, letterSpacing:'-.01em', marginBottom:4 }}>{book.title}</div>
          <div style={{ fontSize:13, opacity:.75 }}>Página {page+1} de {book.pages.length}</div>
          {/* Progress bar */}
          <div style={{ height:4, background:'rgba(255,255,255,.2)', borderRadius:2, marginTop:12 }}>
            <div style={{ height:'100%', background:'rgba(255,255,255,.8)', borderRadius:2, width:`${((page+1)/book.pages.length)*100}%`, transition:'width .3s ease' }}/>
          </div>
        </div>

        {/* Page content */}
        <div style={{ background:'#fff', borderRadius:24, padding:28, boxShadow:'0 1px 4px rgba(4,77,44,.08)', border:'1px solid rgba(10,138,82,.12)', marginBottom:16, minHeight:400 }}>
          <div style={{ fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'.14em', color:mod.color, marginBottom:12 }}>
            {currentPage.title}
          </div>
          <div style={{ fontSize:14, color:'#2E4A3A', lineHeight:1.85, whiteSpace:'pre-wrap' }}>
            {currentPage.content}
          </div>
        </div>

        {/* Navigation */}
        <div style={{ display:'flex', gap:10, marginBottom:20 }}>
          <button onClick={() => setPage(p => Math.max(0, p-1))} disabled={page===0} style={{
            flex:1, padding:'12px', borderRadius:14, border:'1.5px solid rgba(10,138,82,.2)',
            background: page===0 ? '#f5f5f5' : '#fff', color: page===0 ? '#aaa' : '#0D1F17',
            fontFamily:'Outfit,sans-serif', fontSize:13, fontWeight:700, cursor: page===0 ? 'not-allowed' : 'pointer'
          }}>← Página anterior</button>
          <button onClick={() => { if (page < book.pages.length-1) setPage(p => p+1); else { setOpenBook(null); setPage(0) } }} style={{
            flex:1, padding:'12px', borderRadius:14, border:'none',
            background:`linear-gradient(135deg,${mod.color}cc,${mod.color})`,
            color:'#fff', fontFamily:'Outfit,sans-serif', fontSize:13, fontWeight:700, cursor:'pointer'
          }}>{page < book.pages.length-1 ? 'Próxima página →' : '✓ Concluir módulo'}</button>
        </div>

        {/* Page dots */}
        <div style={{ display:'flex', justifyContent:'center', gap:6, flexWrap:'wrap' }}>
          {book.pages.map((_, i) => (
            <button key={i} onClick={() => setPage(i)} style={{
              width:8, height:8, borderRadius:'50%', border:'none', cursor:'pointer', padding:0,
              background: i===page ? mod.color : i<page ? mod.color+'66' : '#D0E8D5'
            }}/>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div style={{ animation:'vIn .26s ease' }}>
      <div style={{ background:'linear-gradient(130deg,#022818,#076B3E)', borderRadius:24, padding:'24px 28px', color:'#fff', marginBottom:20, position:'relative', overflow:'hidden' }}>
        <div style={{ position:'absolute', top:-30, right:-20, width:160, height:160, borderRadius:'50%', background:'rgba(255,255,255,.05)' }}/>
        <div style={{ fontSize:10, fontWeight:700, textTransform:'uppercase', letterSpacing:'.16em', color:'rgba(255,255,255,.55)', marginBottom:8 }}>Curso Completo</div>
        <div style={{ fontSize:22, fontWeight:800, marginBottom:6 }}>Educação Financeira</div>
        <div style={{ fontSize:13, opacity:.75, lineHeight:1.6, marginBottom:16 }}>{MODULES.length} módulos completos com minilivros de 10 páginas cada — do básico ao investidor profissional.</div>
        <div style={{ display:'flex', gap:10, flexWrap:'wrap' }}>
          <div style={{ background:'rgba(255,255,255,.12)', borderRadius:12, padding:'7px 14px', fontSize:12, fontWeight:600 }}>{MODULES.length} módulos</div>
          <div style={{ background:'rgba(255,255,255,.12)', borderRadius:12, padding:'7px 14px', fontSize:12, fontWeight:600 }}>80+ páginas</div>
          <div style={{ background:'rgba(255,255,255,.12)', borderRadius:12, padding:'7px 14px', fontSize:12, fontWeight:600 }}>Certificado</div>
        </div>
      </div>

      <div style={{ display:'grid', gridTemplateColumns:'repeat(auto-fill,minmax(280px,1fr))', gap:14 }}>
        {MODULES.map((m,i) => (
          <div key={i} style={{ borderRadius:24, overflow:'hidden', boxShadow:'0 2px 8px rgba(4,77,44,.1)', cursor:'pointer', transition:'transform .2s, box-shadow .2s' }}
          onClick={() => { setOpenBook(i); setPage(0) }}
          onMouseOver={e=>{e.currentTarget.style.transform='translateY(-3px)';e.currentTarget.style.boxShadow='0 8px 24px rgba(4,77,44,.18)'}}
          onMouseOut={e=>{e.currentTarget.style.transform='translateY(0)';e.currentTarget.style.boxShadow='0 2px 8px rgba(4,77,44,.1)'}}>
            <div style={{ background:m.bg, padding:'18px 20px 14px', borderBottom:`3px solid ${m.color}` }}>
              <div style={{ display:'flex', alignItems:'center', gap:10, marginBottom:8 }}>
                <span style={{ fontSize:26 }}>{m.icon}</span>
                <div>
                  <div style={{ fontSize:9, fontWeight:700, textTransform:'uppercase', letterSpacing:'.12em', color:m.color, opacity:.7, marginBottom:2 }}>Módulo {m.num}</div>
                  <div style={{ fontSize:14, fontWeight:700, color:'#0D1F17' }}>{m.title}</div>
                </div>
              </div>
              <div style={{ fontSize:12, color:'#6B8878', lineHeight:1.55 }}>{m.desc}</div>
            </div>
            <div style={{ background:'#fff', padding:'14px 20px' }}>
              <div style={{ fontSize:9, fontWeight:700, textTransform:'uppercase', letterSpacing:'.12em', color:'#6B8878', marginBottom:8 }}>O que você vai aprender</div>
              {m.topics.map((t,j) => (
                <div key={j} style={{ display:'flex', alignItems:'center', gap:8, fontSize:12, color:'#2E4A3A', padding:'5px 0', borderBottom:j<m.topics.length-1?'1px solid #F0F4F1':'none' }}>
                  <span style={{ color:m.color, fontWeight:700 }}>→</span>{t}
                </div>
              ))}
              <div style={{ marginTop:12, display:'flex', alignItems:'center', justifyContent:'space-between' }}>
                <span style={{ fontSize:11, color:m.color, fontWeight:600 }}>📖 {m.book.pages.length} páginas</span>
                <span style={{ background:m.color, color:'#fff', fontSize:11, fontWeight:700, padding:'4px 12px', borderRadius:20 }}>Ler minilivro →</span>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
